// This file is auto-generated by @hey-api/openapi-ts

export const AgentCreateRequestSchema = {
  properties: {
    name: {
      type: "string",
      maxLength: 160,
      minLength: 3,
      title: "Name",
      description: "Agent name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Agent description",
    },
    llm_provider_id: {
      type: "string",
      title: "Llm Provider Id",
      description: "LLM Provider ID",
    },
    data_source_id: {
      type: "string",
      title: "Data Source Id",
      description: "Data source ID",
    },
    system_prompt: {
      type: "string",
      minLength: 1,
      title: "System Prompt",
      description: "System Prompt",
    },
    user_prompt_template: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "User Prompt Template",
      description: "User input template",
    },
    a2a_card_uri: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "A2A Card Uri",
      description: "A2A Card IPFS URI",
    },
    pricing_model: {
      $ref: "#/components/schemas/PricingModel",
      description: "Pricing model",
    },
    price_amount: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "string",
          pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
        },
        {
          type: "null",
        },
      ],
      title: "Price Amount",
      description: "Price amount",
    },
    currency: {
      anyOf: [
        {
          type: "string",
          maxLength: 16,
        },
        {
          type: "null",
        },
      ],
      title: "Currency",
      description: "Currency",
    },
    requires_user_input: {
      type: "boolean",
      title: "Requires User Input",
      description: "Whether user input is required",
      default: true,
    },
  },
  type: "object",
  required: [
    "name",
    "llm_provider_id",
    "data_source_id",
    "system_prompt",
    "pricing_model",
  ],
  title: "AgentCreateRequest",
  description: `Create Agent request.

Attributes:
    name: Agent name (3-160 characters)
    description: Agent description (optional)
    llm_provider_id: LLM Provider ID
    data_source_id: Data source ID
    system_prompt: System Prompt
    user_prompt_template: User input template (optional)
    a2a_card_uri: A2A Card IPFS URI (optional)
    pricing_model: Pricing model (free/fixed/usage)
    price_amount: Price amount (required when pricing_model is not free)
    currency: Currency (required when pricing_model is not free)
    requires_user_input: Whether user input is required`,
} as const;

export const AgentDetailResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Agent ID",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Agent name",
    },
    owner_wallet: {
      type: "string",
      title: "Owner Wallet",
      description: "Owner wallet address",
    },
    publisher_wallet_address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Publisher Wallet Address",
      description: "Publisher wallet address",
    },
    is_published: {
      type: "boolean",
      title: "Is Published",
      description: "Whether published",
    },
    pricing_model: {
      $ref: "#/components/schemas/PricingModel",
      description: "Pricing model",
    },
    price_amount: {
      anyOf: [
        {
          type: "string",
          pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
        },
        {
          type: "null",
        },
      ],
      title: "Price Amount",
      description: "Price amount",
    },
    currency: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Currency",
      description: "Currency",
    },
    llm_provider_id: {
      type: "string",
      title: "Llm Provider Id",
      description: "LLM Provider ID",
    },
    data_source_id: {
      type: "string",
      title: "Data Source Id",
      description: "Data source ID",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Agent description",
    },
    metadata_uri: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Metadata Uri",
      description: "Metadata IPFS URI",
    },
    a2a_card_uri: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "A2A Card Uri",
      description: "A2A Card IPFS URI",
    },
    system_prompt: {
      type: "string",
      title: "System Prompt",
      description: "System Prompt",
    },
    user_prompt_template: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "User Prompt Template",
      description: "User input template",
    },
    onchain_agent_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Onchain Agent Id",
      description: "On-chain Agent ID",
    },
    onchain_owner_address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Onchain Owner Address",
      description: "On-chain owner address",
    },
    registration_tx_hashes: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Registration Tx Hashes",
      description: "Registration transaction hash list",
    },
    registration_tx_hashes_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Registration Tx Hashes Url",
      description: "Registration transaction URL for the first hash",
    },
    requires_user_input: {
      type: "boolean",
      title: "Requires User Input",
      description: "Whether user input is required",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
      description: "Update time",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "owner_wallet",
    "is_published",
    "pricing_model",
    "llm_provider_id",
    "data_source_id",
    "created_at",
    "system_prompt",
    "requires_user_input",
    "updated_at",
  ],
  title: "AgentDetailResponse",
  description: `Agent detail response.

Inherits from AgentSummary, adding more detailed fields.

Attributes:
    description: Agent description
    metadata_uri: Metadata IPFS URI
    a2a_card_uri: A2A Card IPFS URI
    system_prompt: System Prompt
    user_prompt_template: User input template
    onchain_agent_id: On-chain Agent ID
    onchain_owner_address: On-chain owner address
    registration_tx_hashes: Registration transaction hash list
    registration_tx_hashes_url: Registration transaction URL for the first hash
    requires_user_input: Whether user input is required
    updated_at: Update time`,
} as const;

export const AgentFeedbackJobResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Job ID",
    },
    agent_id: {
      type: "string",
      format: "uuid",
      title: "Agent Id",
      description: "Agent ID",
    },
    status: {
      $ref: "#/components/schemas/JobStatus",
      description: "Job status",
    },
    operation: {
      $ref: "#/components/schemas/FeedbackOperation",
      description: "Operation type",
    },
    tx_hash: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tx Hash",
      description: "Transaction hash",
    },
    error_reason: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Error Reason",
      description: "Failure reason",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
    started_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Started At",
      description: "Start time",
    },
    finished_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Finished At",
      description: "Finish time",
    },
    feedback_index: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Feedback Index",
      description: "Feedback index (off-chain or on-chain)",
    },
    mode: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Mode",
      description: "Execution mode (onchain/offchain)",
    },
    client_wallet: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Wallet",
      description: "Client wallet address",
    },
    feedback_auth: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Feedback Auth",
      description: "Feedback authorization signature (hex)",
    },
    auth_expires_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Auth Expires At",
      description: "Authorization expiration time (UTC)",
    },
  },
  type: "object",
  required: ["id", "agent_id", "status", "operation", "created_at"],
  title: "AgentFeedbackJobResponse",
  description: `Feedback Job Response.

Used to return the status of asynchronous feedback tasks for frontend polling.

Attributes:
    id: Job ID
    agent_id: Agent ID
    status: Job status
    operation: Operation type
    tx_hash: Transaction hash
    error_reason: Failure reason
    created_at: Creation time
    started_at: Start time
    finished_at: Finish time`,
} as const;

export const AgentFeedbackListResponseSchema = {
  properties: {
    total: {
      type: "integer",
      title: "Total",
      description: "Total record count",
    },
    limit: {
      type: "integer",
      title: "Limit",
      description: "Records per page",
    },
    offset: {
      type: "integer",
      title: "Offset",
      description: "Current offset",
    },
    items: {
      items: {
        $ref: "#/components/schemas/AgentFeedbackResponse",
      },
      type: "array",
      title: "Items",
      description: "Feedback list",
    },
  },
  type: "object",
  required: ["total", "limit", "offset", "items"],
  title: "AgentFeedbackListResponse",
  description: `Feedback List Response.

Attributes:
    items: Feedback list
    total: Total count
    limit: Items per page
    offset: Offset`,
} as const;

export const AgentFeedbackRequestSchema = {
  properties: {
    operation: {
      $ref: "#/components/schemas/FeedbackOperation",
      description: "Operation type",
    },
    payload: {
      additionalProperties: true,
      type: "object",
      title: "Payload",
      description: "Feedback data payload",
    },
    feedback_index: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Feedback Index",
      description: "On-chain feedback index",
    },
  },
  type: "object",
  required: ["operation", "payload"],
  title: "AgentFeedbackRequest",
  description: `Feedback Operation Request.

Used to submit, revoke, or respond to feedback.

Attributes:
    operation: Operation type (submit/revoke/respond)
    payload: Feedback data payload, including score, tags, context, etc.
    feedback_index: On-chain feedback index (required for revoke/respond operations)`,
} as const;

export const AgentFeedbackResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Feedback ID",
    },
    agent_id: {
      type: "string",
      format: "uuid",
      title: "Agent Id",
      description: "Agent ID",
    },
    feedback_index: {
      type: "integer",
      title: "Feedback Index",
      description: "On-chain feedback index",
    },
    operation: {
      $ref: "#/components/schemas/FeedbackOperation",
      description: "Operation type",
    },
    requester_wallet: {
      type: "string",
      title: "Requester Wallet",
      description: "Requester wallet address",
    },
    content: {
      additionalProperties: true,
      type: "object",
      title: "Content",
      description: "Complete feedback JSON",
    },
    tx_hash: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tx Hash",
      description: "Transaction hash (empty in offchain mode)",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
  },
  type: "object",
  required: [
    "id",
    "agent_id",
    "feedback_index",
    "operation",
    "requester_wallet",
    "content",
    "created_at",
  ],
  title: "AgentFeedbackResponse",
  description: `Feedback Response.

Attributes:
    id: Feedback ID
    agent_id: Agent ID
    feedback_index: On-chain feedback index
    operation: Operation type
    requester_wallet: Requester wallet address
    content: Complete feedback JSON
    tx_hash: Transaction hash (optional, empty in offchain mode)
    created_at: Creation time`,
} as const;

export const AgentListResponseSchema = {
  properties: {
    total: {
      type: "integer",
      title: "Total",
      description: "Total record count",
    },
    limit: {
      type: "integer",
      title: "Limit",
      description: "Records per page",
    },
    offset: {
      type: "integer",
      title: "Offset",
      description: "Current offset",
    },
    items: {
      items: {
        $ref: "#/components/schemas/AgentSummary",
      },
      type: "array",
      title: "Items",
      description: "Agent list",
    },
  },
  type: "object",
  required: ["total", "limit", "offset", "items"],
  title: "AgentListResponse",
  description: `Agent list response (with pagination).

Attributes:
    total: Total record count
    limit: Records per page
    offset: Current offset
    items: Agent list`,
} as const;

export const AgentPublishJobResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Task ID",
    },
    agent_id: {
      type: "string",
      format: "uuid",
      title: "Agent Id",
      description: "Agent ID",
    },
    status: {
      $ref: "#/components/schemas/JobStatus",
      description: "Task status",
    },
    tx_hash: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tx Hash",
      description: "Transaction hash (deprecated)",
    },
    tx_hashes: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Tx Hashes",
      description: "All transaction hash list",
    },
    onchain_agent_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Onchain Agent Id",
      description: "On-chain Agent ID",
    },
    metadata_uri_snapshot: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Metadata Uri Snapshot",
      description: "Metadata URI snapshot",
    },
    error_reason: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Error Reason",
      description: "Failure reason",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
    started_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Started At",
      description: "Start time",
    },
    finished_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Finished At",
      description: "Completion time",
    },
  },
  type: "object",
  required: ["id", "agent_id", "status", "created_at"],
  title: "AgentPublishJobResponse",
  description: `Agent publish job response.

Used for polling publish job status.

Attributes:
    id: Task ID
    agent_id: Agent ID
    status: Task status (pending/running/succeeded/failed)
    tx_hash: Transaction hash (deprecated, use tx_hashes)
    tx_hashes: All transaction hash list
    onchain_agent_id: On-chain Agent ID (available after success)
    metadata_uri_snapshot: Metadata URI snapshot
    error_reason: Failure reason (optional)
    created_at: Creation time
    started_at: Start time (optional)
    finished_at: Completion time (optional)`,
} as const;

export const AgentPublishRequestSchema = {
  properties: {
    force: {
      type: "boolean",
      title: "Force",
      description: "Whether to force republish",
      default: false,
    },
  },
  type: "object",
  title: "AgentPublishRequest",
  description: `Agent publish request.

Attributes:
    force: Whether to force republish (published Agents can be force updated)`,
} as const;

export const AgentRunCreateRequestSchema = {
  properties: {
    input_payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Input Payload",
      description: "User input data",
    },
    client_context: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Client Context",
      description: "Client context",
    },
  },
  type: "object",
  title: "AgentRunCreateRequest",
  description: `Create Agent Execution Request.

Attributes:
    input_payload: User input data (JSON)
    client_context: Client context information (optional)`,
} as const;

export const AgentRunDetailResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Execution ID",
    },
    agent_id: {
      type: "string",
      format: "uuid",
      title: "Agent Id",
      description: "Agent ID",
    },
    requester_id: {
      type: "string",
      format: "uuid",
      title: "Requester Id",
      description: "Requester ID",
    },
    status: {
      $ref: "#/components/schemas/AgentRunStatus",
      description: "Execution status",
    },
    payment_status: {
      $ref: "#/components/schemas/PaymentStatus",
      description: "Payment status",
    },
    input_payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Input Payload",
      description: "Input data",
    },
    output_payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Output Payload",
      description: "Output result",
    },
    error_reason: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Error Reason",
      description: "Failure reason",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
    started_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Started At",
      description: "Start time",
    },
    finished_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Finished At",
      description: "Completion time",
    },
    events: {
      items: {
        $ref: "#/components/schemas/AgentRunEventResponse",
      },
      type: "array",
      title: "Events",
      description: "Execution event list",
    },
  },
  type: "object",
  required: [
    "id",
    "agent_id",
    "requester_id",
    "status",
    "payment_status",
    "created_at",
  ],
  title: "AgentRunDetailResponse",
  description: `Agent Execution Detail Response.

Extends AgentRunResponse with event list.

Attributes:
    events: Execution event list`,
} as const;

export const AgentRunEventResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Event ID",
    },
    agent_run_id: {
      type: "string",
      format: "uuid",
      title: "Agent Run Id",
      description: "Execution ID",
    },
    event_type: {
      $ref: "#/components/schemas/AgentRunEventType",
      description: "Event type",
    },
    payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Payload",
      description: "Event data",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
  },
  type: "object",
  required: ["id", "agent_run_id", "event_type", "created_at"],
  title: "AgentRunEventResponse",
  description: `Agent Execution Event Response.

Attributes:
    id: Event ID
    agent_run_id: Execution ID
    event_type: Event type
    payload: Event data
    created_at: Creation time`,
} as const;

export const AgentRunEventTypeSchema = {
  type: "string",
  enum: [
    "queued",
    "payment_required",
    "payment_confirmed",
    "datasource_fetch",
    "inference_complete",
    "error",
  ],
  title: "AgentRunEventType",
  description: "Execution event type, used for frontend polling display.",
} as const;

export const AgentRunResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Execution ID",
    },
    agent_id: {
      type: "string",
      format: "uuid",
      title: "Agent Id",
      description: "Agent ID",
    },
    requester_id: {
      type: "string",
      format: "uuid",
      title: "Requester Id",
      description: "Requester ID",
    },
    status: {
      $ref: "#/components/schemas/AgentRunStatus",
      description: "Execution status",
    },
    payment_status: {
      $ref: "#/components/schemas/PaymentStatus",
      description: "Payment status",
    },
    input_payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Input Payload",
      description: "Input data",
    },
    output_payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Output Payload",
      description: "Output result",
    },
    error_reason: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Error Reason",
      description: "Failure reason",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
    started_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Started At",
      description: "Start time",
    },
    finished_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Finished At",
      description: "Completion time",
    },
  },
  type: "object",
  required: [
    "id",
    "agent_id",
    "requester_id",
    "status",
    "payment_status",
    "created_at",
  ],
  title: "AgentRunResponse",
  description: `Agent Execution Response.

This response is returned after payment is completed or when payment is not required.

Attributes:
    id: Execution ID
    agent_id: Agent ID
    requester_id: Requester ID
    status: Execution status
    payment_status: Payment status
    input_payload: Input data
    output_payload: Output result
    error_reason: Failure reason
    created_at: Creation time
    started_at: Start time
    finished_at: Completion time`,
} as const;

export const AgentRunStatusSchema = {
  type: "string",
  enum: ["pending", "paying", "running", "succeeded", "failed", "cancelled"],
  title: "AgentRunStatus",
  description: "Agent execution lifecycle status.",
} as const;

export const AgentSummarySchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Agent ID",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Agent name",
    },
    owner_wallet: {
      type: "string",
      title: "Owner Wallet",
      description: "Owner wallet address",
    },
    publisher_wallet_address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Publisher Wallet Address",
      description: "Publisher wallet address",
    },
    is_published: {
      type: "boolean",
      title: "Is Published",
      description: "Whether published",
    },
    pricing_model: {
      $ref: "#/components/schemas/PricingModel",
      description: "Pricing model",
    },
    price_amount: {
      anyOf: [
        {
          type: "string",
          pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
        },
        {
          type: "null",
        },
      ],
      title: "Price Amount",
      description: "Price amount",
    },
    currency: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Currency",
      description: "Currency",
    },
    llm_provider_id: {
      type: "string",
      title: "Llm Provider Id",
      description: "LLM Provider ID",
    },
    data_source_id: {
      type: "string",
      title: "Data Source Id",
      description: "Data source ID",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
  },
  type: "object",
  required: [
    "id",
    "name",
    "owner_wallet",
    "is_published",
    "pricing_model",
    "llm_provider_id",
    "data_source_id",
    "created_at",
  ],
  title: "AgentSummary",
  description: `Agent summary information (for list display).

Attributes:
    id: Agent ID
    name: Agent name
    owner_wallet: Owner wallet address
    publisher_wallet_address: Publisher wallet address (optional)
    is_published: Whether published
    pricing_model: Pricing model
    price_amount: Price amount
    currency: Currency
    llm_provider_id: LLM Provider ID
    data_source_id: Data source ID
    created_at: Creation time`,
} as const;

export const AgentUpdateRequestSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
          maxLength: 160,
          minLength: 3,
        },
        {
          type: "null",
        },
      ],
      title: "Name",
      description: "Agent name",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
      description: "Agent description",
    },
    llm_provider_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Llm Provider Id",
      description: "LLM Provider ID",
    },
    data_source_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Data Source Id",
      description: "Data source ID",
    },
    system_prompt: {
      anyOf: [
        {
          type: "string",
          minLength: 1,
        },
        {
          type: "null",
        },
      ],
      title: "System Prompt",
      description: "System Prompt",
    },
    user_prompt_template: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "User Prompt Template",
      description: "User input template",
    },
    a2a_card_uri: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "A2A Card Uri",
      description: "A2A Card IPFS URI",
    },
    pricing_model: {
      anyOf: [
        {
          $ref: "#/components/schemas/PricingModel",
        },
        {
          type: "null",
        },
      ],
      description: "Pricing model",
    },
    price_amount: {
      anyOf: [
        {
          type: "number",
          minimum: 0,
        },
        {
          type: "string",
          pattern: "^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$",
        },
        {
          type: "null",
        },
      ],
      title: "Price Amount",
      description: "Price amount",
    },
    currency: {
      anyOf: [
        {
          type: "string",
          maxLength: 16,
        },
        {
          type: "null",
        },
      ],
      title: "Currency",
      description: "Currency",
    },
    requires_user_input: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Requires User Input",
      description: "Whether user input is required",
    },
  },
  type: "object",
  title: "AgentUpdateRequest",
  description: `Update Agent request.

All fields are optional, only provided fields will be updated.

Attributes:
    name: Agent name
    description: Agent description
    llm_provider_id: LLM Provider ID
    data_source_id: Data source ID
    system_prompt: System Prompt
    user_prompt_template: User input template
    a2a_card_uri: A2A Card IPFS URI
    pricing_model: Pricing model
    price_amount: Price amount
    currency: Currency
    requires_user_input: Whether user input is required`,
} as const;

export const AuthChallengeRequestSchema = {
  properties: {
    wallet_address: {
      type: "string",
      pattern: "^0x[a-fA-F0-9]{40}$",
      title: "Wallet Address",
      description: "Wallet address",
      examples: ["0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb0"],
    },
    chain_id: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Chain Id",
      description: "Chain ID",
      examples: [84532],
    },
  },
  type: "object",
  required: ["wallet_address", "chain_id"],
  title: "AuthChallengeRequest",
  description: `Authentication Challenge Request.

Client initiates authentication challenge, server returns a nonce to be signed.

Attributes:
    wallet_address: Wallet address (42-character address starting with 0x)
    chain_id: Chain ID (e.g., Base Sepolia is 84532)`,
} as const;

export const AuthChallengeResponseSchema = {
  properties: {
    nonce: {
      type: "string",
      title: "Nonce",
      description: "Random nonce",
    },
    expires_in: {
      type: "integer",
      title: "Expires In",
      description: "Expiration time (seconds)",
      examples: [300],
    },
    message: {
      type: "string",
      title: "Message",
      description: "Complete message to be signed",
    },
  },
  type: "object",
  required: ["nonce", "expires_in", "message"],
  title: "AuthChallengeResponse",
  description: `Authentication Challenge Response.

Returns a nonce to be signed and expiration time.

Attributes:
    nonce: Random nonce for replay attack prevention
    expires_in: Expiration time (seconds)
    message: Complete message to be signed`,
} as const;

export const AuthLoginRequestSchema = {
  properties: {
    wallet_address: {
      type: "string",
      pattern: "^0x[a-fA-F0-9]{40}$",
      title: "Wallet Address",
      description: "Wallet address",
      examples: ["0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb0"],
    },
    chain_id: {
      type: "integer",
      exclusiveMinimum: 0,
      title: "Chain Id",
      description: "Chain ID",
      examples: [84532],
    },
    signature: {
      type: "string",
      title: "Signature",
      description: "Signature (hex format)",
      examples: ["0x..."],
    },
    nonce: {
      type: "string",
      title: "Nonce",
      description: "Previously obtained nonce",
    },
  },
  type: "object",
  required: ["wallet_address", "chain_id", "signature", "nonce"],
  title: "AuthLoginRequest",
  description: `Login Request.

Client signs the challenge message using wallet private key and submits the signature for verification.

Attributes:
    wallet_address: Wallet address
    chain_id: Chain ID
    signature: Signature (hex format)
    nonce: Previously obtained nonce`,
} as const;

export const AuthLoginResponseSchema = {
  properties: {
    access_token: {
      type: "string",
      title: "Access Token",
      description: "JWT access token",
    },
    token_type: {
      type: "string",
      title: "Token Type",
      description: "Token type",
      default: "bearer",
    },
    expires_in: {
      type: "integer",
      title: "Expires In",
      description: "Token validity period (seconds)",
      examples: [86400],
    },
    user_id: {
      type: "string",
      format: "uuid",
      title: "User Id",
      description: "User ID",
    },
  },
  type: "object",
  required: ["access_token", "expires_in", "user_id"],
  title: "AuthLoginResponse",
  description: `Login Response.

Returns JWT access token and user information.

Attributes:
    access_token: JWT access token
    token_type: Token type, fixed as "bearer"
    expires_in: Token validity period (seconds)
    user_id: User ID`,
} as const;

export const DataSourceResponseSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "DataSource ID",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Data source name",
    },
    type: {
      type: "string",
      title: "Type",
      description: "Data source type",
    },
    input_description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Input Description",
      description: "Input description",
    },
    output_description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Output Description",
      description: "Output description",
    },
  },
  type: "object",
  required: ["id", "name", "type"],
  title: "DataSourceResponse",
  description: `DataSource response.

Attributes:
    id: DataSource ID
    name: Data source name
    type: Data source type
    input_description: Input description
    output_description: Output description`,
} as const;

export const FeedbackAuthRequestSchema = {
  properties: {
    client_wallet: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Wallet",
      description: "Client wallet address (defaults to current user)",
    },
    expiry_hours: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Expiry Hours",
      description: "Authorization validity period (hours)",
      default: 24,
    },
    max_index_hint: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Max Index Hint",
      description: "Optional feedback index upper limit hint",
    },
  },
  type: "object",
  title: "FeedbackAuthRequest",
  description: "Feedback Authorization Request.",
} as const;

export const FeedbackOperationSchema = {
  type: "string",
  enum: [
    "submit",
    "revoke",
    "respond",
    "sign_auth",
    "sync_submit",
    "sync_revoke",
  ],
  title: "FeedbackOperation",
  description: "Feedback operation type.",
} as const;

export const FeedbackReceiptRequestSchema = {
  properties: {
    operation: {
      $ref: "#/components/schemas/FeedbackOperation",
      description: "Operation type (submit/revoke only)",
    },
    client_wallet: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Client Wallet",
      description: "Client wallet address (defaults to current user)",
    },
    feedback_index: {
      type: "integer",
      title: "Feedback Index",
      description: "On-chain feedback index",
    },
    tx_hash: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tx Hash",
      description:
        "On-chain transaction hash (optional, for additional verification)",
    },
    file_uri: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "File Uri",
      description: "IPFS file URI",
    },
    payload: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Payload",
      description: "Payload when submitted on-chain (optional)",
    },
    proof_of_payment: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Proof Of Payment",
      description: "Proof of payment (optional)",
    },
  },
  type: "object",
  required: ["operation", "feedback_index"],
  title: "FeedbackReceiptRequest",
  description: "Client On-chain Feedback Receipt Request.",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const IDResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "Resource ID",
    },
  },
  type: "object",
  required: ["id"],
  title: "IDResponse",
  description: `ID Response (for create operations).

Attributes:
    id: ID of the created resource`,
} as const;

export const JobStatusSchema = {
  type: "string",
  enum: ["pending", "running", "succeeded", "failed"],
  title: "JobStatus",
  description: "Asynchronous task status.",
} as const;

export const LLMProviderResponseSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Provider ID",
    },
    vendor: {
      type: "string",
      title: "Vendor",
      description: "Vendor name",
    },
    model: {
      type: "string",
      title: "Model",
      description: "Model name",
    },
    max_tokens: {
      type: "integer",
      title: "Max Tokens",
      description: "Maximum token count",
    },
    rpm_limit: {
      type: "integer",
      title: "Rpm Limit",
      description: "Requests per minute limit",
    },
  },
  type: "object",
  required: ["id", "vendor", "model", "max_tokens", "rpm_limit"],
  title: "LLMProviderResponse",
  description: `LLM Provider response.

Attributes:
    id: Provider ID
    vendor: Vendor name
    model: Model name
    max_tokens: Maximum token count
    rpm_limit: Requests per minute limit`,
} as const;

export const PaginatedResponse_AgentRunResponse_Schema = {
  properties: {
    total: {
      type: "integer",
      title: "Total",
      description: "Total record count",
    },
    limit: {
      type: "integer",
      title: "Limit",
      description: "Records per page",
    },
    offset: {
      type: "integer",
      title: "Offset",
      description: "Current offset",
    },
    items: {
      items: {
        $ref: "#/components/schemas/AgentRunResponse",
      },
      type: "array",
      title: "Items",
      description: "Data list",
    },
  },
  type: "object",
  required: ["total", "limit", "offset", "items"],
  title: "PaginatedResponse[AgentRunResponse]",
} as const;

export const PaymentRequiredResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
      description: "Status: payment_required",
      default: "payment_required",
    },
    agent_run_id: {
      type: "string",
      format: "uuid",
      title: "Agent Run Id",
      description: "Created Agent Run ID",
    },
    payment_id: {
      type: "string",
      format: "uuid",
      title: "Payment Id",
      description: "Payment record ID",
    },
    x402_version: {
      type: "string",
      title: "X402 Version",
      description: "x402 protocol version",
    },
    payment_requirements: {
      items: {
        additionalProperties: true,
        type: "object",
      },
      type: "array",
      title: "Payment Requirements",
      description: "Payment requirements list",
    },
    error: {
      type: "string",
      title: "Error",
      description: "Error message",
      default: "Payment required",
    },
  },
  type: "object",
  required: [
    "agent_run_id",
    "payment_id",
    "x402_version",
    "payment_requirements",
  ],
  title: "PaymentRequiredResponse",
  description: `402 response returned when first call requires payment.

This response tells the client that payment is required to continue.`,
} as const;

export const PaymentStatusSchema = {
  type: "string",
  enum: [
    "none",
    "required",
    "pending_signature",
    "pending",
    "confirmed",
    "failed",
  ],
  title: "PaymentStatus",
  description: `x402 payment state machine.

State transition description:
- NONE: No payment required
- REQUIRED: API returns 402, waiting for frontend to initiate signature
- PENDING_SIGNATURE: User clicked payment but signature not completed
- PENDING: Signature submitted, facilitator processing
- CONFIRMED: Payment completed, can proceed to execution
- FAILED: Payment failed or timed out`,
} as const;

export const PricingModelSchema = {
  type: "string",
  enum: ["free", "fixed", "usage"],
  title: "PricingModel",
  description: "Agent pricing model.",
} as const;

export const UserProfileResponseSchema = {
  properties: {
    id: {
      type: "string",
      format: "uuid",
      title: "Id",
      description: "User ID",
    },
    wallet_address: {
      type: "string",
      title: "Wallet Address",
      description: "Wallet address",
    },
    chain_id: {
      type: "integer",
      title: "Chain Id",
      description: "Chain ID",
    },
    display_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Display Name",
      description: "Display name",
    },
    email: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Email",
      description: "Email",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
  },
  type: "object",
  required: ["id", "wallet_address", "chain_id", "created_at"],
  title: "UserProfileResponse",
  description: `User Profile Response.

Returns detailed information of the currently logged-in user.

Attributes:
    id: User ID
    wallet_address: Wallet address
    chain_id: Chain ID
    display_name: Display name (optional)
    email: Email (optional)
    created_at: Creation time`,
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
