// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import {
  createFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponseTransformer,
  getAgentApiV1AgentsAgentIdGetResponseTransformer,
  getAgentRunApiV1AgentsAgentIdRunsRunIdGetResponseTransformer,
  getCurrentUserProfileApiV1AuthMeGetResponseTransformer,
  getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponseTransformer,
  getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponseTransformer,
  listAgentsApiV1AgentsGetResponseTransformer,
  listFeedbacksApiV1AgentsAgentIdFeedbackGetResponseTransformer,
  listMyAgentsApiV1MeAgentsGetResponseTransformer,
  listMyRunsApiV1MeRunsGetResponseTransformer,
  publishAgentApiV1AgentsAgentIdPublishPostResponseTransformer,
  submitFeedbackApiV1AgentsAgentIdFeedbackPostResponseTransformer,
  submitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponseTransformer,
  updateAgentApiV1AgentsAgentIdPutResponseTransformer,
} from "./transformers.gen";
import type {
  CreateAgentApiV1AgentsPostData,
  CreateAgentApiV1AgentsPostErrors,
  CreateAgentApiV1AgentsPostResponses,
  CreateAgentRunApiV1AgentsAgentIdRunsPostData,
  CreateAgentRunApiV1AgentsAgentIdRunsPostErrors,
  CreateAgentRunApiV1AgentsAgentIdRunsPostResponses,
  CreateChallengeApiV1AuthChallengePostData,
  CreateChallengeApiV1AuthChallengePostErrors,
  CreateChallengeApiV1AuthChallengePostResponses,
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostData,
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostErrors,
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponses,
  DeleteAgentApiV1AgentsAgentIdDeleteData,
  DeleteAgentApiV1AgentsAgentIdDeleteErrors,
  DeleteAgentApiV1AgentsAgentIdDeleteResponses,
  GetAgentApiV1AgentsAgentIdGetData,
  GetAgentApiV1AgentsAgentIdGetErrors,
  GetAgentApiV1AgentsAgentIdGetResponses,
  GetAgentRunApiV1AgentsAgentIdRunsRunIdGetData,
  GetAgentRunApiV1AgentsAgentIdRunsRunIdGetErrors,
  GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponses,
  GetCurrentUserProfileApiV1AuthMeGetData,
  GetCurrentUserProfileApiV1AuthMeGetResponses,
  GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetData,
  GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetErrors,
  GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponses,
  GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetData,
  GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetErrors,
  GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponses,
  HealthHealthGetData,
  HealthHealthGetResponses,
  ListAgentsApiV1AgentsGetData,
  ListAgentsApiV1AgentsGetErrors,
  ListAgentsApiV1AgentsGetResponses,
  ListDataSourcesApiV1ConfigDataSourcesGetData,
  ListDataSourcesApiV1ConfigDataSourcesGetResponses,
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetData,
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetErrors,
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponses,
  ListLlmProvidersApiV1ConfigLlmProvidersGetData,
  ListLlmProvidersApiV1ConfigLlmProvidersGetResponses,
  ListMyAgentsApiV1MeAgentsGetData,
  ListMyAgentsApiV1MeAgentsGetErrors,
  ListMyAgentsApiV1MeAgentsGetResponses,
  ListMyRunsApiV1MeRunsGetData,
  ListMyRunsApiV1MeRunsGetErrors,
  ListMyRunsApiV1MeRunsGetResponses,
  LoginApiV1AuthLoginPostData,
  LoginApiV1AuthLoginPostErrors,
  LoginApiV1AuthLoginPostResponses,
  PublishAgentApiV1AgentsAgentIdPublishPostData,
  PublishAgentApiV1AgentsAgentIdPublishPostErrors,
  PublishAgentApiV1AgentsAgentIdPublishPostResponses,
  RootGetData,
  RootGetResponses,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostData,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostErrors,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponses,
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostData,
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostErrors,
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponses,
  UpdateAgentApiV1AgentsAgentIdPutData,
  UpdateAgentApiV1AgentsAgentIdPutErrors,
  UpdateAgentApiV1AgentsAgentIdPutResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get authentication challenge
 *
 * Get authentication challenge.
 *
 * Client provides wallet address and chain ID, server returns nonce and message to sign.
 *
 * Args:
 * request: Authentication challenge request
 *
 * Returns:
 * Authentication challenge response with nonce and message to sign
 *
 * Raises:
 * HTTPException: If cache is full, returns 429 Too Many Requests
 */
export const createChallengeApiV1AuthChallengePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateChallengeApiV1AuthChallengePostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateChallengeApiV1AuthChallengePostResponses,
    CreateChallengeApiV1AuthChallengePostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/challenge",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Login
 *
 * User login.
 *
 * Client signs the challenge message with wallet private key and submits the signature for verification.
 * Returns JWT access token upon successful verification.
 *
 * Args:
 * request: Login request
 *
 * Returns:
 * Login response with JWT access token and user information
 *
 * Raises:
 * HTTPException: If signature verification fails
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    LoginApiV1AuthLoginPostResponses,
    LoginApiV1AuthLoginPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get current user information
 *
 * Get current logged-in user profile.
 *
 * Requires valid JWT token in request header.
 *
 * Args:
 * current_user: Current user (injected via dependency)
 *
 * Returns:
 * User profile response
 */
export const getCurrentUserProfileApiV1AuthMeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCurrentUserProfileApiV1AuthMeGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCurrentUserProfileApiV1AuthMeGetResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getCurrentUserProfileApiV1AuthMeGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/me",
    ...options,
  });
};

/**
 * Query Agent List
 *
 * Query Agent list (supports pagination and filtering).
 *
 * No authentication required, but unauthenticated users can only see published Agents.
 * Authenticated users can see all their own Agents and published Agents from others.
 *
 * Args:
 * pagination: Pagination parameters
 * is_published: Whether published (optional)
 * owner_id: Owner ID (optional)
 * llm_provider_id: LLM Provider ID (optional)
 * search: Search keyword (optional)
 * current_user: Current user (optional, via dependency injection)
 *
 * Returns:
 * Agent list response
 *
 * Raises:
 * HTTPException: If unauthenticated user tries to query Agents of a specific owner
 */
export const listAgentsApiV1AgentsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListAgentsApiV1AgentsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListAgentsApiV1AgentsGetResponses,
    ListAgentsApiV1AgentsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listAgentsApiV1AgentsGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents",
    ...options,
  });
};

/**
 * Create Agent
 *
 * Create a new Agent.
 *
 * Requires authentication. Only draft status Agents can be created, which can be published to chain later via the publish endpoint.
 *
 * Args:
 * request: Agent creation request
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Created Agent ID
 *
 * Raises:
 * HTTPException: If LLM Provider or DataSource does not exist
 */
export const createAgentApiV1AgentsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateAgentApiV1AgentsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateAgentApiV1AgentsPostResponses,
    CreateAgentApiV1AgentsPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Agent
 *
 * Delete Agent.
 *
 * Requires authentication, only the owner can delete.
 *
 * Args:
 * agent_id: Agent ID
 * current_user: Current user (via dependency injection)
 *
 * Raises:
 * HTTPException: If Agent does not exist or no permission
 */
export const deleteAgentApiV1AgentsAgentIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteAgentApiV1AgentsAgentIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteAgentApiV1AgentsAgentIdDeleteResponses,
    DeleteAgentApiV1AgentsAgentIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}",
    ...options,
  });
};

/**
 * Get Agent Details
 *
 * Get Agent details.
 *
 * No authentication required, but only the owner can view unpublished Agents.
 *
 * Args:
 * agent_id: Agent ID
 * current_user: Current user (optional, via dependency injection)
 *
 * Returns:
 * Agent detail response
 *
 * Raises:
 * HTTPException: If Agent does not exist or no permission to access
 */
export const getAgentApiV1AgentsAgentIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAgentApiV1AgentsAgentIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAgentApiV1AgentsAgentIdGetResponses,
    GetAgentApiV1AgentsAgentIdGetErrors,
    ThrowOnError
  >({
    responseTransformer: getAgentApiV1AgentsAgentIdGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}",
    ...options,
  });
};

/**
 * Update Agent
 *
 * Update Agent.
 *
 * Requires authentication, only the owner can update. Only updates the provided fields.
 *
 * Args:
 * agent_id: Agent ID
 * request: Agent update request
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Updated Agent details
 *
 * Raises:
 * HTTPException: If Agent does not exist, no permission, or update failed
 */
export const updateAgentApiV1AgentsAgentIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateAgentApiV1AgentsAgentIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateAgentApiV1AgentsAgentIdPutResponses,
    UpdateAgentApiV1AgentsAgentIdPutErrors,
    ThrowOnError
  >({
    responseTransformer: updateAgentApiV1AgentsAgentIdPutResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Publish Agent to Chain
 *
 * Publish Agent to chain.
 *
 * Requires authentication, only the owner can publish. Creates an async publish task and returns task ID.
 *
 * Args:
 * agent_id: Agent ID
 * request: Publish request (includes force parameter)
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Publish task details
 *
 * Raises:
 * HTTPException: If Agent does not exist, no permission, or task creation failed
 */
export const publishAgentApiV1AgentsAgentIdPublishPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PublishAgentApiV1AgentsAgentIdPublishPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PublishAgentApiV1AgentsAgentIdPublishPostResponses,
    PublishAgentApiV1AgentsAgentIdPublishPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      publishAgentApiV1AgentsAgentIdPublishPostResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/publish",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Query Publish Task Status
 *
 * Query Agent publish task status.
 *
 * Used to poll publish progress.
 *
 * Args:
 * agent_id: Agent ID
 * job_id: Task ID
 * current_user: Current user (optional, via dependency injection)
 *
 * Returns:
 * Publish task details
 *
 * Raises:
 * HTTPException: If task does not exist or Agent ID does not match
 */
export const getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponses,
    GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/publish-jobs/{job_id}",
    ...options,
  });
};

/**
 * Execute Agent
 *
 * Initiate Agent run.
 *
 * Requires authentication. Creates run instance and triggers async task.
 *
 * **Payment Flow**:
 * 1. First call: If Agent requires payment, creates run record and returns 402 status with payment requirements
 * 2. Second call: With X-PAYMENT header, verifies payment then triggers run task
 *
 * Args:
 * agent_id: Agent ID
 * request_body: run request (contains input data)
 * fastapi_request: FastAPI Request object
 * current_user: current user (via dependency injection)
 * x_payment: X-PAYMENT header (optional, provided on second request)
 *
 * Returns:
 * - 202: AgentRunResponse - run created
 * - 402: PaymentRequiredResponse - payment required
 *
 * Raises:
 * HTTPException: if Agent doesn't exist or operation fails
 */
export const createAgentRunApiV1AgentsAgentIdRunsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateAgentRunApiV1AgentsAgentIdRunsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateAgentRunApiV1AgentsAgentIdRunsPostResponses,
    CreateAgentRunApiV1AgentsAgentIdRunsPostErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/runs",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Query Agent run status
 *
 * Query Agent run status.
 *
 * Used for polling run progress. Requires authentication, can only query own runs.
 *
 * Args:
 * agent_id: Agent ID
 * run_id: run ID
 * current_user: current user (via dependency injection)
 *
 * Returns:
 * run details (including event list)
 *
 * Raises:
 * HTTPException: if run doesn't exist or no permission
 */
export const getAgentRunApiV1AgentsAgentIdRunsRunIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAgentRunApiV1AgentsAgentIdRunsRunIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponses,
    GetAgentRunApiV1AgentsAgentIdRunsRunIdGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getAgentRunApiV1AgentsAgentIdRunsRunIdGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/runs/{run_id}",
    ...options,
  });
};

/**
 * Query feedback list
 *
 * Query feedback list for Agent.
 *
 * Supports pagination and operation type filtering. No authentication required, everyone can view feedback.
 *
 * Args:
 * agent_id: Agent ID
 * pagination: Pagination parameters
 * operation: Operation type filter (optional)
 *
 * Returns:
 * Feedback list response
 */
export const listFeedbacksApiV1AgentsAgentIdFeedbackGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListFeedbacksApiV1AgentsAgentIdFeedbackGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponses,
    ListFeedbacksApiV1AgentsAgentIdFeedbackGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      listFeedbacksApiV1AgentsAgentIdFeedbackGetResponseTransformer,
    url: "/api/v1/agents/{agent_id}/feedback",
    ...options,
  });
};

/**
 * Submit/revoke/respond to feedback
 *
 * Submit, revoke, or append response to feedback.
 *
 * Currently only supports the respond operation; for submit/revoke use the auth + receipts flow.
 *
 * Authentication required. Only published Agents can accept feedback.
 *
 * Args:
 * agent_id: Agent ID
 * request: Feedback request
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Feedback job response (task will be processed asynchronously)
 *
 * Raises:
 * HTTPException: If Agent does not exist, is not published, or user lacks permission
 */
export const submitFeedbackApiV1AgentsAgentIdFeedbackPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitFeedbackApiV1AgentsAgentIdFeedbackPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponses,
    SubmitFeedbackApiV1AgentsAgentIdFeedbackPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      submitFeedbackApiV1AgentsAgentIdFeedbackPostResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Generate feedback authorization
 *
 * Generate feedback authorization signature.
 */
export const createFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponses,
    CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      createFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/feedback/auth",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Sync on-chain feedback receipt
 *
 * Submit feedback receipt signed by client.
 */
export const submitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).post<
    SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponses,
    SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostErrors,
    ThrowOnError
  >({
    responseTransformer:
      submitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/feedback/receipts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Query feedback job status
 *
 * Query feedback job status.
 *
 * Used by frontend to poll task progress. Authentication required, can only query own tasks or completed tasks.
 *
 * Args:
 * agent_id: Agent ID (for path completeness, not actually used)
 * job_id: Task ID
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Feedback job response
 *
 * Raises:
 * HTTPException: If task does not exist or no permission
 */
export const getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponses,
    GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetErrors,
    ThrowOnError
  >({
    responseTransformer:
      getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/agents/{agent_id}/feedback/jobs/{job_id}",
    ...options,
  });
};

/**
 * View My Agents
 *
 * List all Agents created by the current user.
 *
 * Includes both published and unpublished Agents.
 * Requires authentication.
 *
 * Args:
 * current_user: Current user (via dependency injection)
 * pagination: Pagination parameters
 *
 * Returns:
 * Paginated list of Agents
 */
export const listMyAgentsApiV1MeAgentsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListMyAgentsApiV1MeAgentsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListMyAgentsApiV1MeAgentsGetResponses,
    ListMyAgentsApiV1MeAgentsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listMyAgentsApiV1MeAgentsGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/me/agents",
    ...options,
  });
};

/**
 * View My Execution History
 *
 * View all Agent execution history initiated by the current user.
 *
 * Returns in descending order by creation time.
 * Requires authentication.
 *
 * Args:
 * current_user: Current user (via dependency injection)
 * pagination: Pagination parameters
 *
 * Returns:
 * Paginated list of execution history
 */
export const listMyRunsApiV1MeRunsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListMyRunsApiV1MeRunsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListMyRunsApiV1MeRunsGetResponses,
    ListMyRunsApiV1MeRunsGetErrors,
    ThrowOnError
  >({
    responseTransformer: listMyRunsApiV1MeRunsGetResponseTransformer,
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/me/runs",
    ...options,
  });
};

/**
 * Query LLM Provider List
 *
 * Query available LLM Provider list.
 *
 * No authentication required, returns all configured LLM Providers.
 *
 * Returns:
 * List of LLM Providers
 */
export const listLlmProvidersApiV1ConfigLlmProvidersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListLlmProvidersApiV1ConfigLlmProvidersGetData,
    ThrowOnError
  >,
) => {
  return (options?.client ?? client).get<
    ListLlmProvidersApiV1ConfigLlmProvidersGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/config/llm-providers",
    ...options,
  });
};

/**
 * Query DataSource List
 *
 * Query available DataSource list.
 *
 * No authentication required, returns all configured DataSources.
 *
 * Returns:
 * List of DataSources
 */
export const listDataSourcesApiV1ConfigDataSourcesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListDataSourcesApiV1ConfigDataSourcesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListDataSourcesApiV1ConfigDataSourcesGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/config/data-sources",
    ...options,
  });
};

/**
 * Root
 *
 * Root path health check.
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    RootGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/",
    ...options,
  });
};

/**
 * Health
 *
 * Health check endpoint.
 *
 * Checks the status of critical dependencies like database, Redis, Celery, etc.
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health",
    ...options,
  });
};
