// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponse,
  GetAgentApiV1AgentsAgentIdGetResponse,
  GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponse,
  GetCurrentUserProfileApiV1AuthMeGetResponse,
  GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponse,
  GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponse,
  ListAgentsApiV1AgentsGetResponse,
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponse,
  ListMyAgentsApiV1MeAgentsGetResponse,
  ListMyRunsApiV1MeRunsGetResponse,
  PublishAgentApiV1AgentsAgentIdPublishPostResponse,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponse,
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponse,
  UpdateAgentApiV1AgentsAgentIdPutResponse,
} from "./types.gen";

const userProfileResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const getCurrentUserProfileApiV1AuthMeGetResponseTransformer = async (
  data: any,
): Promise<GetCurrentUserProfileApiV1AuthMeGetResponse> => {
  data = userProfileResponseSchemaResponseTransformer(data);
  return data;
};

const agentListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return agentSummarySchemaResponseTransformer(item);
  });
  return data;
};

const agentSummarySchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const listAgentsApiV1AgentsGetResponseTransformer = async (
  data: any,
): Promise<ListAgentsApiV1AgentsGetResponse> => {
  data = agentListResponseSchemaResponseTransformer(data);
  return data;
};

const agentDetailResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const getAgentApiV1AgentsAgentIdGetResponseTransformer = async (
  data: any,
): Promise<GetAgentApiV1AgentsAgentIdGetResponse> => {
  data = agentDetailResponseSchemaResponseTransformer(data);
  return data;
};

export const updateAgentApiV1AgentsAgentIdPutResponseTransformer = async (
  data: any,
): Promise<UpdateAgentApiV1AgentsAgentIdPutResponse> => {
  data = agentDetailResponseSchemaResponseTransformer(data);
  return data;
};

const agentPublishJobResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.finished_at) {
    data.finished_at = new Date(data.finished_at);
  }
  return data;
};

export const publishAgentApiV1AgentsAgentIdPublishPostResponseTransformer =
  async (
    data: any,
  ): Promise<PublishAgentApiV1AgentsAgentIdPublishPostResponse> => {
    data = agentPublishJobResponseSchemaResponseTransformer(data);
    return data;
  };

export const getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponse> => {
    data = agentPublishJobResponseSchemaResponseTransformer(data);
    return data;
  };

const agentRunDetailResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.finished_at) {
    data.finished_at = new Date(data.finished_at);
  }
  if (data.events) {
    data.events = data.events.map((item: any) => {
      return agentRunEventResponseSchemaResponseTransformer(item);
    });
  }
  return data;
};

const agentRunEventResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const getAgentRunApiV1AgentsAgentIdRunsRunIdGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponse> => {
    data = agentRunDetailResponseSchemaResponseTransformer(data);
    return data;
  };

const agentFeedbackListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return agentFeedbackResponseSchemaResponseTransformer(item);
  });
  return data;
};

const agentFeedbackResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  return data;
};

export const listFeedbacksApiV1AgentsAgentIdFeedbackGetResponseTransformer =
  async (
    data: any,
  ): Promise<ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponse> => {
    data = agentFeedbackListResponseSchemaResponseTransformer(data);
    return data;
  };

const agentFeedbackJobResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.finished_at) {
    data.finished_at = new Date(data.finished_at);
  }
  if (data.auth_expires_at) {
    data.auth_expires_at = new Date(data.auth_expires_at);
  }
  return data;
};

export const submitFeedbackApiV1AgentsAgentIdFeedbackPostResponseTransformer =
  async (
    data: any,
  ): Promise<SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponse> => {
    data = agentFeedbackJobResponseSchemaResponseTransformer(data);
    return data;
  };

export const createFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponseTransformer =
  async (
    data: any,
  ): Promise<CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponse> => {
    data = agentFeedbackJobResponseSchemaResponseTransformer(data);
    return data;
  };

export const submitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponseTransformer =
  async (
    data: any,
  ): Promise<SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponse> => {
    data = agentFeedbackJobResponseSchemaResponseTransformer(data);
    return data;
  };

export const getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponseTransformer =
  async (
    data: any,
  ): Promise<GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponse> => {
    data = agentFeedbackJobResponseSchemaResponseTransformer(data);
    return data;
  };

export const listMyAgentsApiV1MeAgentsGetResponseTransformer = async (
  data: any,
): Promise<ListMyAgentsApiV1MeAgentsGetResponse> => {
  data = agentListResponseSchemaResponseTransformer(data);
  return data;
};

const paginatedResponseAgentRunResponseSchemaResponseTransformer = (
  data: any,
) => {
  data.items = data.items.map((item: any) => {
    return agentRunResponseSchemaResponseTransformer(item);
  });
  return data;
};

const agentRunResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  if (data.started_at) {
    data.started_at = new Date(data.started_at);
  }
  if (data.finished_at) {
    data.finished_at = new Date(data.finished_at);
  }
  return data;
};

export const listMyRunsApiV1MeRunsGetResponseTransformer = async (
  data: any,
): Promise<ListMyRunsApiV1MeRunsGetResponse> => {
  data = paginatedResponseAgentRunResponseSchemaResponseTransformer(data);
  return data;
};
