// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AgentCreateRequest
 *
 * Create Agent request.
 *
 * Attributes:
 * name: Agent name (3-160 characters)
 * description: Agent description (optional)
 * llm_provider_id: LLM Provider ID
 * data_source_id: Data source ID
 * system_prompt: System Prompt
 * user_prompt_template: User input template (optional)
 * a2a_card_uri: A2A Card IPFS URI (optional)
 * pricing_model: Pricing model (free/fixed/usage)
 * price_amount: Price amount (required when pricing_model is not free)
 * currency: Currency (required when pricing_model is not free)
 * requires_user_input: Whether user input is required
 */
export type AgentCreateRequest = {
  /**
   * Name
   *
   * Agent name
   */
  name: string;
  /**
   * Description
   *
   * Agent description
   */
  description?: string | null;
  /**
   * Llm Provider Id
   *
   * LLM Provider ID
   */
  llm_provider_id: string;
  /**
   * Data Source Id
   *
   * Data source ID
   */
  data_source_id: string;
  /**
   * System Prompt
   *
   * System Prompt
   */
  system_prompt: string;
  /**
   * User Prompt Template
   *
   * User input template
   */
  user_prompt_template?: string | null;
  /**
   * A2A Card Uri
   *
   * A2A Card IPFS URI
   */
  a2a_card_uri?: string | null;
  /**
   * Pricing model
   */
  pricing_model: PricingModel;
  /**
   * Price Amount
   *
   * Price amount
   */
  price_amount?: number | string | null;
  /**
   * Currency
   *
   * Currency
   */
  currency?: string | null;
  /**
   * Requires User Input
   *
   * Whether user input is required
   */
  requires_user_input?: boolean;
};

/**
 * AgentDetailResponse
 *
 * Agent detail response.
 *
 * Inherits from AgentSummary, adding more detailed fields.
 *
 * Attributes:
 * description: Agent description
 * metadata_uri: Metadata IPFS URI
 * a2a_card_uri: A2A Card IPFS URI
 * system_prompt: System Prompt
 * user_prompt_template: User input template
 * onchain_agent_id: On-chain Agent ID
 * onchain_owner_address: On-chain owner address
 * registration_tx_hashes: Registration transaction hash list
 * registration_tx_hashes_url: Registration transaction URL for the first hash
 * requires_user_input: Whether user input is required
 * updated_at: Update time
 */
export type AgentDetailResponse = {
  /**
   * Id
   *
   * Agent ID
   */
  id: string;
  /**
   * Name
   *
   * Agent name
   */
  name: string;
  /**
   * Owner Wallet
   *
   * Owner wallet address
   */
  owner_wallet: string;
  /**
   * Publisher Wallet Address
   *
   * Publisher wallet address
   */
  publisher_wallet_address?: string | null;
  /**
   * Is Published
   *
   * Whether published
   */
  is_published: boolean;
  /**
   * Pricing model
   */
  pricing_model: PricingModel;
  /**
   * Price Amount
   *
   * Price amount
   */
  price_amount?: string | null;
  /**
   * Currency
   *
   * Currency
   */
  currency?: string | null;
  /**
   * Llm Provider Id
   *
   * LLM Provider ID
   */
  llm_provider_id: string;
  /**
   * Data Source Id
   *
   * Data source ID
   */
  data_source_id: string;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
  /**
   * Description
   *
   * Agent description
   */
  description?: string | null;
  /**
   * Metadata Uri
   *
   * Metadata IPFS URI
   */
  metadata_uri?: string | null;
  /**
   * A2A Card Uri
   *
   * A2A Card IPFS URI
   */
  a2a_card_uri?: string | null;
  /**
   * System Prompt
   *
   * System Prompt
   */
  system_prompt: string;
  /**
   * User Prompt Template
   *
   * User input template
   */
  user_prompt_template?: string | null;
  /**
   * Onchain Agent Id
   *
   * On-chain Agent ID
   */
  onchain_agent_id?: string | null;
  /**
   * Onchain Owner Address
   *
   * On-chain owner address
   */
  onchain_owner_address?: string | null;
  /**
   * Registration Tx Hashes
   *
   * Registration transaction hash list
   */
  registration_tx_hashes?: Array<string> | null;
  /**
   * Registration Tx Hashes Url
   *
   * Registration transaction URL for the first hash
   */
  registration_tx_hashes_url?: string | null;
  /**
   * Requires User Input
   *
   * Whether user input is required
   */
  requires_user_input: boolean;
  /**
   * Updated At
   *
   * Update time
   */
  updated_at: Date;
};

/**
 * AgentFeedbackJobResponse
 *
 * Feedback Job Response.
 *
 * Used to return the status of asynchronous feedback tasks for frontend polling.
 *
 * Attributes:
 * id: Job ID
 * agent_id: Agent ID
 * status: Job status
 * operation: Operation type
 * tx_hash: Transaction hash
 * error_reason: Failure reason
 * created_at: Creation time
 * started_at: Start time
 * finished_at: Finish time
 */
export type AgentFeedbackJobResponse = {
  /**
   * Id
   *
   * Job ID
   */
  id: string;
  /**
   * Agent Id
   *
   * Agent ID
   */
  agent_id: string;
  /**
   * Job status
   */
  status: JobStatus;
  /**
   * Operation type
   */
  operation: FeedbackOperation;
  /**
   * Tx Hash
   *
   * Transaction hash
   */
  tx_hash?: string | null;
  /**
   * Error Reason
   *
   * Failure reason
   */
  error_reason?: string | null;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
  /**
   * Started At
   *
   * Start time
   */
  started_at?: Date | null;
  /**
   * Finished At
   *
   * Finish time
   */
  finished_at?: Date | null;
  /**
   * Feedback Index
   *
   * Feedback index (off-chain or on-chain)
   */
  feedback_index?: number | null;
  /**
   * Mode
   *
   * Execution mode (onchain/offchain)
   */
  mode?: string | null;
  /**
   * Client Wallet
   *
   * Client wallet address
   */
  client_wallet?: string | null;
  /**
   * Feedback Auth
   *
   * Feedback authorization signature (hex)
   */
  feedback_auth?: string | null;
  /**
   * Auth Expires At
   *
   * Authorization expiration time (UTC)
   */
  auth_expires_at?: Date | null;
};

/**
 * AgentFeedbackListResponse
 *
 * Feedback List Response.
 *
 * Attributes:
 * items: Feedback list
 * total: Total count
 * limit: Items per page
 * offset: Offset
 */
export type AgentFeedbackListResponse = {
  /**
   * Total
   *
   * Total record count
   */
  total: number;
  /**
   * Limit
   *
   * Records per page
   */
  limit: number;
  /**
   * Offset
   *
   * Current offset
   */
  offset: number;
  /**
   * Items
   *
   * Feedback list
   */
  items: Array<AgentFeedbackResponse>;
};

/**
 * AgentFeedbackRequest
 *
 * Feedback Operation Request.
 *
 * Used to submit, revoke, or respond to feedback.
 *
 * Attributes:
 * operation: Operation type (submit/revoke/respond)
 * payload: Feedback data payload, including score, tags, context, etc.
 * feedback_index: On-chain feedback index (required for revoke/respond operations)
 */
export type AgentFeedbackRequest = {
  /**
   * Operation type
   */
  operation: FeedbackOperation;
  /**
   * Payload
   *
   * Feedback data payload
   */
  payload: {
    [key: string]: unknown;
  };
  /**
   * Feedback Index
   *
   * On-chain feedback index
   */
  feedback_index?: number | null;
};

/**
 * AgentFeedbackResponse
 *
 * Feedback Response.
 *
 * Attributes:
 * id: Feedback ID
 * agent_id: Agent ID
 * feedback_index: On-chain feedback index
 * operation: Operation type
 * requester_wallet: Requester wallet address
 * content: Complete feedback JSON
 * tx_hash: Transaction hash (optional, empty in offchain mode)
 * created_at: Creation time
 */
export type AgentFeedbackResponse = {
  /**
   * Id
   *
   * Feedback ID
   */
  id: string;
  /**
   * Agent Id
   *
   * Agent ID
   */
  agent_id: string;
  /**
   * Feedback Index
   *
   * On-chain feedback index
   */
  feedback_index: number;
  /**
   * Operation type
   */
  operation: FeedbackOperation;
  /**
   * Requester Wallet
   *
   * Requester wallet address
   */
  requester_wallet: string;
  /**
   * Content
   *
   * Complete feedback JSON
   */
  content: {
    [key: string]: unknown;
  };
  /**
   * Tx Hash
   *
   * Transaction hash (empty in offchain mode)
   */
  tx_hash?: string | null;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
};

/**
 * AgentListResponse
 *
 * Agent list response (with pagination).
 *
 * Attributes:
 * total: Total record count
 * limit: Records per page
 * offset: Current offset
 * items: Agent list
 */
export type AgentListResponse = {
  /**
   * Total
   *
   * Total record count
   */
  total: number;
  /**
   * Limit
   *
   * Records per page
   */
  limit: number;
  /**
   * Offset
   *
   * Current offset
   */
  offset: number;
  /**
   * Items
   *
   * Agent list
   */
  items: Array<AgentSummary>;
};

/**
 * AgentPublishJobResponse
 *
 * Agent publish job response.
 *
 * Used for polling publish job status.
 *
 * Attributes:
 * id: Task ID
 * agent_id: Agent ID
 * status: Task status (pending/running/succeeded/failed)
 * tx_hash: Transaction hash (deprecated, use tx_hashes)
 * tx_hashes: All transaction hash list
 * onchain_agent_id: On-chain Agent ID (available after success)
 * metadata_uri_snapshot: Metadata URI snapshot
 * error_reason: Failure reason (optional)
 * created_at: Creation time
 * started_at: Start time (optional)
 * finished_at: Completion time (optional)
 */
export type AgentPublishJobResponse = {
  /**
   * Id
   *
   * Task ID
   */
  id: string;
  /**
   * Agent Id
   *
   * Agent ID
   */
  agent_id: string;
  /**
   * Task status
   */
  status: JobStatus;
  /**
   * Tx Hash
   *
   * Transaction hash (deprecated)
   */
  tx_hash?: string | null;
  /**
   * Tx Hashes
   *
   * All transaction hash list
   */
  tx_hashes?: Array<string> | null;
  /**
   * Onchain Agent Id
   *
   * On-chain Agent ID
   */
  onchain_agent_id?: string | null;
  /**
   * Metadata Uri Snapshot
   *
   * Metadata URI snapshot
   */
  metadata_uri_snapshot?: string | null;
  /**
   * Error Reason
   *
   * Failure reason
   */
  error_reason?: string | null;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
  /**
   * Started At
   *
   * Start time
   */
  started_at?: Date | null;
  /**
   * Finished At
   *
   * Completion time
   */
  finished_at?: Date | null;
};

/**
 * AgentPublishRequest
 *
 * Agent publish request.
 *
 * Attributes:
 * force: Whether to force republish (published Agents can be force updated)
 */
export type AgentPublishRequest = {
  /**
   * Force
   *
   * Whether to force republish
   */
  force?: boolean;
};

/**
 * AgentRunCreateRequest
 *
 * Create Agent Execution Request.
 *
 * Attributes:
 * input_payload: User input data (JSON)
 * client_context: Client context information (optional)
 */
export type AgentRunCreateRequest = {
  /**
   * Input Payload
   *
   * User input data
   */
  input_payload?: {
    [key: string]: unknown;
  } | null;
  /**
   * Client Context
   *
   * Client context
   */
  client_context?: {
    [key: string]: unknown;
  } | null;
};

/**
 * AgentRunDetailResponse
 *
 * Agent Execution Detail Response.
 *
 * Extends AgentRunResponse with event list.
 *
 * Attributes:
 * events: Execution event list
 */
export type AgentRunDetailResponse = {
  /**
   * Id
   *
   * Execution ID
   */
  id: string;
  /**
   * Agent Id
   *
   * Agent ID
   */
  agent_id: string;
  /**
   * Requester Id
   *
   * Requester ID
   */
  requester_id: string;
  /**
   * Execution status
   */
  status: AgentRunStatus;
  /**
   * Payment status
   */
  payment_status: PaymentStatus;
  /**
   * Input Payload
   *
   * Input data
   */
  input_payload?: {
    [key: string]: unknown;
  } | null;
  /**
   * Output Payload
   *
   * Output result
   */
  output_payload?: {
    [key: string]: unknown;
  } | null;
  /**
   * Error Reason
   *
   * Failure reason
   */
  error_reason?: string | null;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
  /**
   * Started At
   *
   * Start time
   */
  started_at?: Date | null;
  /**
   * Finished At
   *
   * Completion time
   */
  finished_at?: Date | null;
  /**
   * Events
   *
   * Execution event list
   */
  events?: Array<AgentRunEventResponse>;
};

/**
 * AgentRunEventResponse
 *
 * Agent Execution Event Response.
 *
 * Attributes:
 * id: Event ID
 * agent_run_id: Execution ID
 * event_type: Event type
 * payload: Event data
 * created_at: Creation time
 */
export type AgentRunEventResponse = {
  /**
   * Id
   *
   * Event ID
   */
  id: string;
  /**
   * Agent Run Id
   *
   * Execution ID
   */
  agent_run_id: string;
  /**
   * Event type
   */
  event_type: AgentRunEventType;
  /**
   * Payload
   *
   * Event data
   */
  payload?: {
    [key: string]: unknown;
  } | null;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
};

/**
 * AgentRunEventType
 *
 * Execution event type, used for frontend polling display.
 */
export const AgentRunEventType = {
  QUEUED: "queued",
  PAYMENT_REQUIRED: "payment_required",
  PAYMENT_CONFIRMED: "payment_confirmed",
  DATASOURCE_FETCH: "datasource_fetch",
  INFERENCE_COMPLETE: "inference_complete",
  ERROR: "error",
} as const;

/**
 * AgentRunEventType
 *
 * Execution event type, used for frontend polling display.
 */
export type AgentRunEventType =
  (typeof AgentRunEventType)[keyof typeof AgentRunEventType];

/**
 * AgentRunResponse
 *
 * Agent Execution Response.
 *
 * This response is returned after payment is completed or when payment is not required.
 *
 * Attributes:
 * id: Execution ID
 * agent_id: Agent ID
 * requester_id: Requester ID
 * status: Execution status
 * payment_status: Payment status
 * input_payload: Input data
 * output_payload: Output result
 * error_reason: Failure reason
 * created_at: Creation time
 * started_at: Start time
 * finished_at: Completion time
 */
export type AgentRunResponse = {
  /**
   * Id
   *
   * Execution ID
   */
  id: string;
  /**
   * Agent Id
   *
   * Agent ID
   */
  agent_id: string;
  /**
   * Requester Id
   *
   * Requester ID
   */
  requester_id: string;
  /**
   * Execution status
   */
  status: AgentRunStatus;
  /**
   * Payment status
   */
  payment_status: PaymentStatus;
  /**
   * Input Payload
   *
   * Input data
   */
  input_payload?: {
    [key: string]: unknown;
  } | null;
  /**
   * Output Payload
   *
   * Output result
   */
  output_payload?: {
    [key: string]: unknown;
  } | null;
  /**
   * Error Reason
   *
   * Failure reason
   */
  error_reason?: string | null;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
  /**
   * Started At
   *
   * Start time
   */
  started_at?: Date | null;
  /**
   * Finished At
   *
   * Completion time
   */
  finished_at?: Date | null;
};

/**
 * AgentRunStatus
 *
 * Agent execution lifecycle status.
 */
export const AgentRunStatus = {
  PENDING: "pending",
  PAYING: "paying",
  RUNNING: "running",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
  CANCELLED: "cancelled",
} as const;

/**
 * AgentRunStatus
 *
 * Agent execution lifecycle status.
 */
export type AgentRunStatus =
  (typeof AgentRunStatus)[keyof typeof AgentRunStatus];

/**
 * AgentSummary
 *
 * Agent summary information (for list display).
 *
 * Attributes:
 * id: Agent ID
 * name: Agent name
 * owner_wallet: Owner wallet address
 * publisher_wallet_address: Publisher wallet address (optional)
 * is_published: Whether published
 * pricing_model: Pricing model
 * price_amount: Price amount
 * currency: Currency
 * llm_provider_id: LLM Provider ID
 * data_source_id: Data source ID
 * created_at: Creation time
 */
export type AgentSummary = {
  /**
   * Id
   *
   * Agent ID
   */
  id: string;
  /**
   * Name
   *
   * Agent name
   */
  name: string;
  /**
   * Owner Wallet
   *
   * Owner wallet address
   */
  owner_wallet: string;
  /**
   * Publisher Wallet Address
   *
   * Publisher wallet address
   */
  publisher_wallet_address?: string | null;
  /**
   * Is Published
   *
   * Whether published
   */
  is_published: boolean;
  /**
   * Pricing model
   */
  pricing_model: PricingModel;
  /**
   * Price Amount
   *
   * Price amount
   */
  price_amount?: string | null;
  /**
   * Currency
   *
   * Currency
   */
  currency?: string | null;
  /**
   * Llm Provider Id
   *
   * LLM Provider ID
   */
  llm_provider_id: string;
  /**
   * Data Source Id
   *
   * Data source ID
   */
  data_source_id: string;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
};

/**
 * AgentUpdateRequest
 *
 * Update Agent request.
 *
 * All fields are optional, only provided fields will be updated.
 *
 * Attributes:
 * name: Agent name
 * description: Agent description
 * llm_provider_id: LLM Provider ID
 * data_source_id: Data source ID
 * system_prompt: System Prompt
 * user_prompt_template: User input template
 * a2a_card_uri: A2A Card IPFS URI
 * pricing_model: Pricing model
 * price_amount: Price amount
 * currency: Currency
 * requires_user_input: Whether user input is required
 */
export type AgentUpdateRequest = {
  /**
   * Name
   *
   * Agent name
   */
  name?: string | null;
  /**
   * Description
   *
   * Agent description
   */
  description?: string | null;
  /**
   * Llm Provider Id
   *
   * LLM Provider ID
   */
  llm_provider_id?: string | null;
  /**
   * Data Source Id
   *
   * Data source ID
   */
  data_source_id?: string | null;
  /**
   * System Prompt
   *
   * System Prompt
   */
  system_prompt?: string | null;
  /**
   * User Prompt Template
   *
   * User input template
   */
  user_prompt_template?: string | null;
  /**
   * A2A Card Uri
   *
   * A2A Card IPFS URI
   */
  a2a_card_uri?: string | null;
  /**
   * Pricing model
   */
  pricing_model?: PricingModel | null;
  /**
   * Price Amount
   *
   * Price amount
   */
  price_amount?: number | string | null;
  /**
   * Currency
   *
   * Currency
   */
  currency?: string | null;
  /**
   * Requires User Input
   *
   * Whether user input is required
   */
  requires_user_input?: boolean | null;
};

/**
 * AuthChallengeRequest
 *
 * Authentication Challenge Request.
 *
 * Client initiates authentication challenge, server returns a nonce to be signed.
 *
 * Attributes:
 * wallet_address: Wallet address (42-character address starting with 0x)
 * chain_id: Chain ID (e.g., Base Sepolia is 84532)
 */
export type AuthChallengeRequest = {
  /**
   * Wallet Address
   *
   * Wallet address
   */
  wallet_address: string;
  /**
   * Chain Id
   *
   * Chain ID
   */
  chain_id: number;
};

/**
 * AuthChallengeResponse
 *
 * Authentication Challenge Response.
 *
 * Returns a nonce to be signed and expiration time.
 *
 * Attributes:
 * nonce: Random nonce for replay attack prevention
 * expires_in: Expiration time (seconds)
 * message: Complete message to be signed
 */
export type AuthChallengeResponse = {
  /**
   * Nonce
   *
   * Random nonce
   */
  nonce: string;
  /**
   * Expires In
   *
   * Expiration time (seconds)
   */
  expires_in: number;
  /**
   * Message
   *
   * Complete message to be signed
   */
  message: string;
};

/**
 * AuthLoginRequest
 *
 * Login Request.
 *
 * Client signs the challenge message using wallet private key and submits the signature for verification.
 *
 * Attributes:
 * wallet_address: Wallet address
 * chain_id: Chain ID
 * signature: Signature (hex format)
 * nonce: Previously obtained nonce
 */
export type AuthLoginRequest = {
  /**
   * Wallet Address
   *
   * Wallet address
   */
  wallet_address: string;
  /**
   * Chain Id
   *
   * Chain ID
   */
  chain_id: number;
  /**
   * Signature
   *
   * Signature (hex format)
   */
  signature: string;
  /**
   * Nonce
   *
   * Previously obtained nonce
   */
  nonce: string;
};

/**
 * AuthLoginResponse
 *
 * Login Response.
 *
 * Returns JWT access token and user information.
 *
 * Attributes:
 * access_token: JWT access token
 * token_type: Token type, fixed as "bearer"
 * expires_in: Token validity period (seconds)
 * user_id: User ID
 */
export type AuthLoginResponse = {
  /**
   * Access Token
   *
   * JWT access token
   */
  access_token: string;
  /**
   * Token Type
   *
   * Token type
   */
  token_type?: string;
  /**
   * Expires In
   *
   * Token validity period (seconds)
   */
  expires_in: number;
  /**
   * User Id
   *
   * User ID
   */
  user_id: string;
};

/**
 * DataSourceResponse
 *
 * DataSource response.
 *
 * Attributes:
 * id: DataSource ID
 * name: Data source name
 * type: Data source type
 * input_description: Input description
 * output_description: Output description
 */
export type DataSourceResponse = {
  /**
   * Id
   *
   * DataSource ID
   */
  id: string;
  /**
   * Name
   *
   * Data source name
   */
  name: string;
  /**
   * Type
   *
   * Data source type
   */
  type: string;
  /**
   * Input Description
   *
   * Input description
   */
  input_description?: string | null;
  /**
   * Output Description
   *
   * Output description
   */
  output_description?: string | null;
};

/**
 * FeedbackAuthRequest
 *
 * Feedback Authorization Request.
 */
export type FeedbackAuthRequest = {
  /**
   * Client Wallet
   *
   * Client wallet address (defaults to current user)
   */
  client_wallet?: string | null;
  /**
   * Expiry Hours
   *
   * Authorization validity period (hours)
   */
  expiry_hours?: number | null;
  /**
   * Max Index Hint
   *
   * Optional feedback index upper limit hint
   */
  max_index_hint?: number | null;
};

/**
 * FeedbackOperation
 *
 * Feedback operation type.
 */
export const FeedbackOperation = {
  SUBMIT: "submit",
  REVOKE: "revoke",
  RESPOND: "respond",
  SIGN_AUTH: "sign_auth",
  SYNC_SUBMIT: "sync_submit",
  SYNC_REVOKE: "sync_revoke",
} as const;

/**
 * FeedbackOperation
 *
 * Feedback operation type.
 */
export type FeedbackOperation =
  (typeof FeedbackOperation)[keyof typeof FeedbackOperation];

/**
 * FeedbackReceiptRequest
 *
 * Client On-chain Feedback Receipt Request.
 */
export type FeedbackReceiptRequest = {
  /**
   * Operation type (submit/revoke only)
   */
  operation: FeedbackOperation;
  /**
   * Client Wallet
   *
   * Client wallet address (defaults to current user)
   */
  client_wallet?: string | null;
  /**
   * Feedback Index
   *
   * On-chain feedback index
   */
  feedback_index: number;
  /**
   * Tx Hash
   *
   * On-chain transaction hash (optional, for additional verification)
   */
  tx_hash?: string | null;
  /**
   * File Uri
   *
   * IPFS file URI
   */
  file_uri?: string | null;
  /**
   * Payload
   *
   * Payload when submitted on-chain (optional)
   */
  payload?: {
    [key: string]: unknown;
  } | null;
  /**
   * Proof Of Payment
   *
   * Proof of payment (optional)
   */
  proof_of_payment?: {
    [key: string]: unknown;
  } | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * IDResponse
 *
 * ID Response (for create operations).
 *
 * Attributes:
 * id: ID of the created resource
 */
export type IdResponse = {
  /**
   * Id
   *
   * Resource ID
   */
  id: string;
};

/**
 * JobStatus
 *
 * Asynchronous task status.
 */
export const JobStatus = {
  PENDING: "pending",
  RUNNING: "running",
  SUCCEEDED: "succeeded",
  FAILED: "failed",
} as const;

/**
 * JobStatus
 *
 * Asynchronous task status.
 */
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];

/**
 * LLMProviderResponse
 *
 * LLM Provider response.
 *
 * Attributes:
 * id: Provider ID
 * vendor: Vendor name
 * model: Model name
 * max_tokens: Maximum token count
 * rpm_limit: Requests per minute limit
 */
export type LlmProviderResponse = {
  /**
   * Id
   *
   * Provider ID
   */
  id: string;
  /**
   * Vendor
   *
   * Vendor name
   */
  vendor: string;
  /**
   * Model
   *
   * Model name
   */
  model: string;
  /**
   * Max Tokens
   *
   * Maximum token count
   */
  max_tokens: number;
  /**
   * Rpm Limit
   *
   * Requests per minute limit
   */
  rpm_limit: number;
};

/**
 * PaginatedResponse[AgentRunResponse]
 */
export type PaginatedResponseAgentRunResponse = {
  /**
   * Total
   *
   * Total record count
   */
  total: number;
  /**
   * Limit
   *
   * Records per page
   */
  limit: number;
  /**
   * Offset
   *
   * Current offset
   */
  offset: number;
  /**
   * Items
   *
   * Data list
   */
  items: Array<AgentRunResponse>;
};

/**
 * PaymentRequiredResponse
 *
 * 402 response returned when first call requires payment.
 *
 * This response tells the client that payment is required to continue.
 */
export type PaymentRequiredResponse = {
  /**
   * Status
   *
   * Status: payment_required
   */
  status?: string;
  /**
   * Agent Run Id
   *
   * Created Agent Run ID
   */
  agent_run_id: string;
  /**
   * Payment Id
   *
   * Payment record ID
   */
  payment_id: string;
  /**
   * X402 Version
   *
   * x402 protocol version
   */
  x402_version: string;
  /**
   * Payment Requirements
   *
   * Payment requirements list
   */
  payment_requirements: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Error
   *
   * Error message
   */
  error?: string;
};

/**
 * PaymentStatus
 *
 * x402 payment state machine.
 *
 * State transition description:
 * - NONE: No payment required
 * - REQUIRED: API returns 402, waiting for frontend to initiate signature
 * - PENDING_SIGNATURE: User clicked payment but signature not completed
 * - PENDING: Signature submitted, facilitator processing
 * - CONFIRMED: Payment completed, can proceed to execution
 * - FAILED: Payment failed or timed out
 */
export const PaymentStatus = {
  NONE: "none",
  REQUIRED: "required",
  PENDING_SIGNATURE: "pending_signature",
  PENDING: "pending",
  CONFIRMED: "confirmed",
  FAILED: "failed",
} as const;

/**
 * PaymentStatus
 *
 * x402 payment state machine.
 *
 * State transition description:
 * - NONE: No payment required
 * - REQUIRED: API returns 402, waiting for frontend to initiate signature
 * - PENDING_SIGNATURE: User clicked payment but signature not completed
 * - PENDING: Signature submitted, facilitator processing
 * - CONFIRMED: Payment completed, can proceed to execution
 * - FAILED: Payment failed or timed out
 */
export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];

/**
 * PricingModel
 *
 * Agent pricing model.
 */
export const PricingModel = {
  FREE: "free",
  FIXED: "fixed",
  USAGE: "usage",
} as const;

/**
 * PricingModel
 *
 * Agent pricing model.
 */
export type PricingModel = (typeof PricingModel)[keyof typeof PricingModel];

/**
 * UserProfileResponse
 *
 * User Profile Response.
 *
 * Returns detailed information of the currently logged-in user.
 *
 * Attributes:
 * id: User ID
 * wallet_address: Wallet address
 * chain_id: Chain ID
 * display_name: Display name (optional)
 * email: Email (optional)
 * created_at: Creation time
 */
export type UserProfileResponse = {
  /**
   * Id
   *
   * User ID
   */
  id: string;
  /**
   * Wallet Address
   *
   * Wallet address
   */
  wallet_address: string;
  /**
   * Chain Id
   *
   * Chain ID
   */
  chain_id: number;
  /**
   * Display Name
   *
   * Display name
   */
  display_name?: string | null;
  /**
   * Email
   *
   * Email
   */
  email?: string | null;
  /**
   * Created At
   *
   * Creation time
   */
  created_at: Date;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type CreateChallengeApiV1AuthChallengePostData = {
  body: AuthChallengeRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/challenge";
};

export type CreateChallengeApiV1AuthChallengePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateChallengeApiV1AuthChallengePostError =
  CreateChallengeApiV1AuthChallengePostErrors[keyof CreateChallengeApiV1AuthChallengePostErrors];

export type CreateChallengeApiV1AuthChallengePostResponses = {
  /**
   * Successful Response
   */
  200: AuthChallengeResponse;
};

export type CreateChallengeApiV1AuthChallengePostResponse =
  CreateChallengeApiV1AuthChallengePostResponses[keyof CreateChallengeApiV1AuthChallengePostResponses];

export type LoginApiV1AuthLoginPostData = {
  body: AuthLoginRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/login";
};

export type LoginApiV1AuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError =
  LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: AuthLoginResponse;
};

export type LoginApiV1AuthLoginPostResponse =
  LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type GetCurrentUserProfileApiV1AuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type GetCurrentUserProfileApiV1AuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserProfileResponse;
};

export type GetCurrentUserProfileApiV1AuthMeGetResponse =
  GetCurrentUserProfileApiV1AuthMeGetResponses[keyof GetCurrentUserProfileApiV1AuthMeGetResponses];

export type ListAgentsApiV1AgentsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Is Published
     *
     * Whether published
     */
    is_published?: boolean | null;
    /**
     * Owner Id
     *
     * Owner ID
     */
    owner_id?: string | null;
    /**
     * Llm Provider Id
     *
     * LLM Provider ID
     */
    llm_provider_id?: string | null;
    /**
     * Search
     *
     * Search keyword
     */
    search?: string | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/agents";
};

export type ListAgentsApiV1AgentsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAgentsApiV1AgentsGetError =
  ListAgentsApiV1AgentsGetErrors[keyof ListAgentsApiV1AgentsGetErrors];

export type ListAgentsApiV1AgentsGetResponses = {
  /**
   * Successful Response
   */
  200: AgentListResponse;
};

export type ListAgentsApiV1AgentsGetResponse =
  ListAgentsApiV1AgentsGetResponses[keyof ListAgentsApiV1AgentsGetResponses];

export type CreateAgentApiV1AgentsPostData = {
  body: AgentCreateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/agents";
};

export type CreateAgentApiV1AgentsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAgentApiV1AgentsPostError =
  CreateAgentApiV1AgentsPostErrors[keyof CreateAgentApiV1AgentsPostErrors];

export type CreateAgentApiV1AgentsPostResponses = {
  /**
   * Successful Response
   */
  201: IdResponse;
};

export type CreateAgentApiV1AgentsPostResponse =
  CreateAgentApiV1AgentsPostResponses[keyof CreateAgentApiV1AgentsPostResponses];

export type DeleteAgentApiV1AgentsAgentIdDeleteData = {
  body?: never;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}";
};

export type DeleteAgentApiV1AgentsAgentIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteAgentApiV1AgentsAgentIdDeleteError =
  DeleteAgentApiV1AgentsAgentIdDeleteErrors[keyof DeleteAgentApiV1AgentsAgentIdDeleteErrors];

export type DeleteAgentApiV1AgentsAgentIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteAgentApiV1AgentsAgentIdDeleteResponse =
  DeleteAgentApiV1AgentsAgentIdDeleteResponses[keyof DeleteAgentApiV1AgentsAgentIdDeleteResponses];

export type GetAgentApiV1AgentsAgentIdGetData = {
  body?: never;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}";
};

export type GetAgentApiV1AgentsAgentIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAgentApiV1AgentsAgentIdGetError =
  GetAgentApiV1AgentsAgentIdGetErrors[keyof GetAgentApiV1AgentsAgentIdGetErrors];

export type GetAgentApiV1AgentsAgentIdGetResponses = {
  /**
   * Successful Response
   */
  200: AgentDetailResponse;
};

export type GetAgentApiV1AgentsAgentIdGetResponse =
  GetAgentApiV1AgentsAgentIdGetResponses[keyof GetAgentApiV1AgentsAgentIdGetResponses];

export type UpdateAgentApiV1AgentsAgentIdPutData = {
  body: AgentUpdateRequest;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}";
};

export type UpdateAgentApiV1AgentsAgentIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateAgentApiV1AgentsAgentIdPutError =
  UpdateAgentApiV1AgentsAgentIdPutErrors[keyof UpdateAgentApiV1AgentsAgentIdPutErrors];

export type UpdateAgentApiV1AgentsAgentIdPutResponses = {
  /**
   * Successful Response
   */
  200: AgentDetailResponse;
};

export type UpdateAgentApiV1AgentsAgentIdPutResponse =
  UpdateAgentApiV1AgentsAgentIdPutResponses[keyof UpdateAgentApiV1AgentsAgentIdPutResponses];

export type PublishAgentApiV1AgentsAgentIdPublishPostData = {
  body: AgentPublishRequest;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/publish";
};

export type PublishAgentApiV1AgentsAgentIdPublishPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PublishAgentApiV1AgentsAgentIdPublishPostError =
  PublishAgentApiV1AgentsAgentIdPublishPostErrors[keyof PublishAgentApiV1AgentsAgentIdPublishPostErrors];

export type PublishAgentApiV1AgentsAgentIdPublishPostResponses = {
  /**
   * Successful Response
   */
  202: AgentPublishJobResponse;
};

export type PublishAgentApiV1AgentsAgentIdPublishPostResponse =
  PublishAgentApiV1AgentsAgentIdPublishPostResponses[keyof PublishAgentApiV1AgentsAgentIdPublishPostResponses];

export type GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetData = {
  body?: never;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Job Id
     */
    job_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/publish-jobs/{job_id}";
};

export type GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetError =
  GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetErrors[keyof GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetErrors];

export type GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponses = {
  /**
   * Successful Response
   */
  200: AgentPublishJobResponse;
};

export type GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponse =
  GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponses[keyof GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetResponses];

export type CreateAgentRunApiV1AgentsAgentIdRunsPostData = {
  body: AgentRunCreateRequest;
  headers?: {
    /**
     * X-Payment
     */
    "X-PAYMENT"?: string | null;
  };
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/runs";
};

export type CreateAgentRunApiV1AgentsAgentIdRunsPostErrors = {
  /**
   * Payment required
   */
  402: PaymentRequiredResponse;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateAgentRunApiV1AgentsAgentIdRunsPostError =
  CreateAgentRunApiV1AgentsAgentIdRunsPostErrors[keyof CreateAgentRunApiV1AgentsAgentIdRunsPostErrors];

export type CreateAgentRunApiV1AgentsAgentIdRunsPostResponses = {
  /**
   * Response Create Agent Run Api V1 Agents  Agent Id  Runs Post
   *
   * Successful Response
   */
  200: AgentRunResponse | PaymentRequiredResponse;
  /**
   * Agent run created
   */
  202: AgentRunResponse;
};

export type CreateAgentRunApiV1AgentsAgentIdRunsPostResponse =
  CreateAgentRunApiV1AgentsAgentIdRunsPostResponses[keyof CreateAgentRunApiV1AgentsAgentIdRunsPostResponses];

export type GetAgentRunApiV1AgentsAgentIdRunsRunIdGetData = {
  body?: never;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Run Id
     */
    run_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/runs/{run_id}";
};

export type GetAgentRunApiV1AgentsAgentIdRunsRunIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAgentRunApiV1AgentsAgentIdRunsRunIdGetError =
  GetAgentRunApiV1AgentsAgentIdRunsRunIdGetErrors[keyof GetAgentRunApiV1AgentsAgentIdRunsRunIdGetErrors];

export type GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponses = {
  /**
   * Successful Response
   */
  200: AgentRunDetailResponse;
};

export type GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponse =
  GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponses[keyof GetAgentRunApiV1AgentsAgentIdRunsRunIdGetResponses];

export type ListFeedbacksApiV1AgentsAgentIdFeedbackGetData = {
  body?: never;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: {
    /**
     * Operation
     *
     * Operation type filter
     */
    operation?: FeedbackOperation | null;
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/agents/{agent_id}/feedback";
};

export type ListFeedbacksApiV1AgentsAgentIdFeedbackGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListFeedbacksApiV1AgentsAgentIdFeedbackGetError =
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetErrors[keyof ListFeedbacksApiV1AgentsAgentIdFeedbackGetErrors];

export type ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponses = {
  /**
   * Successful Response
   */
  200: AgentFeedbackListResponse;
};

export type ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponse =
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponses[keyof ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponses];

export type SubmitFeedbackApiV1AgentsAgentIdFeedbackPostData = {
  body: AgentFeedbackRequest;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/feedback";
};

export type SubmitFeedbackApiV1AgentsAgentIdFeedbackPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SubmitFeedbackApiV1AgentsAgentIdFeedbackPostError =
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostErrors[keyof SubmitFeedbackApiV1AgentsAgentIdFeedbackPostErrors];

export type SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponses = {
  /**
   * Successful Response
   */
  202: AgentFeedbackJobResponse;
};

export type SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponse =
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponses[keyof SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponses];

export type CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostData = {
  body: FeedbackAuthRequest;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/feedback/auth";
};

export type CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostError =
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostErrors[keyof CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostErrors];

export type CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponses = {
  /**
   * Successful Response
   */
  202: AgentFeedbackJobResponse;
};

export type CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponse =
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponses[keyof CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponses];

export type SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostData = {
  body: FeedbackReceiptRequest;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/feedback/receipts";
};

export type SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostError =
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostErrors[keyof SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostErrors];

export type SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponses =
  {
    /**
     * Successful Response
     */
    202: AgentFeedbackJobResponse;
  };

export type SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponse =
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponses[keyof SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponses];

export type GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetData = {
  body?: never;
  path: {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Job Id
     */
    job_id: string;
  };
  query?: never;
  url: "/api/v1/agents/{agent_id}/feedback/jobs/{job_id}";
};

export type GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetError =
  GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetErrors[keyof GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetErrors];

export type GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponses = {
  /**
   * Successful Response
   */
  200: AgentFeedbackJobResponse;
};

export type GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponse =
  GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponses[keyof GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetResponses];

export type ListMyAgentsApiV1MeAgentsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/me/agents";
};

export type ListMyAgentsApiV1MeAgentsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListMyAgentsApiV1MeAgentsGetError =
  ListMyAgentsApiV1MeAgentsGetErrors[keyof ListMyAgentsApiV1MeAgentsGetErrors];

export type ListMyAgentsApiV1MeAgentsGetResponses = {
  /**
   * Successful Response
   */
  200: AgentListResponse;
};

export type ListMyAgentsApiV1MeAgentsGetResponse =
  ListMyAgentsApiV1MeAgentsGetResponses[keyof ListMyAgentsApiV1MeAgentsGetResponses];

export type ListMyRunsApiV1MeRunsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
    /**
     * Offset
     */
    offset?: number;
  };
  url: "/api/v1/me/runs";
};

export type ListMyRunsApiV1MeRunsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListMyRunsApiV1MeRunsGetError =
  ListMyRunsApiV1MeRunsGetErrors[keyof ListMyRunsApiV1MeRunsGetErrors];

export type ListMyRunsApiV1MeRunsGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedResponseAgentRunResponse;
};

export type ListMyRunsApiV1MeRunsGetResponse =
  ListMyRunsApiV1MeRunsGetResponses[keyof ListMyRunsApiV1MeRunsGetResponses];

export type ListLlmProvidersApiV1ConfigLlmProvidersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/llm-providers";
};

export type ListLlmProvidersApiV1ConfigLlmProvidersGetResponses = {
  /**
   * Response List Llm Providers Api V1 Config Llm Providers Get
   *
   * Successful Response
   */
  200: Array<LlmProviderResponse>;
};

export type ListLlmProvidersApiV1ConfigLlmProvidersGetResponse =
  ListLlmProvidersApiV1ConfigLlmProvidersGetResponses[keyof ListLlmProvidersApiV1ConfigLlmProvidersGetResponses];

export type ListDataSourcesApiV1ConfigDataSourcesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/config/data-sources";
};

export type ListDataSourcesApiV1ConfigDataSourcesGetResponses = {
  /**
   * Response List Data Sources Api V1 Config Data Sources Get
   *
   * Successful Response
   */
  200: Array<DataSourceResponse>;
};

export type ListDataSourcesApiV1ConfigDataSourcesGetResponse =
  ListDataSourcesApiV1ConfigDataSourcesGetResponses[keyof ListDataSourcesApiV1ConfigDataSourcesGetResponses];

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type HealthHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: unknown;
  };
};

export type HealthHealthGetResponse =
  HealthHealthGetResponses[keyof HealthHealthGetResponses];
