// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createAgentApiV1AgentsPost,
  createAgentRunApiV1AgentsAgentIdRunsPost,
  createChallengeApiV1AuthChallengePost,
  createFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPost,
  deleteAgentApiV1AgentsAgentIdDelete,
  getAgentApiV1AgentsAgentIdGet,
  getAgentRunApiV1AgentsAgentIdRunsRunIdGet,
  getCurrentUserProfileApiV1AuthMeGet,
  getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGet,
  getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGet,
  healthHealthGet,
  listAgentsApiV1AgentsGet,
  listDataSourcesApiV1ConfigDataSourcesGet,
  listFeedbacksApiV1AgentsAgentIdFeedbackGet,
  listLlmProvidersApiV1ConfigLlmProvidersGet,
  listMyAgentsApiV1MeAgentsGet,
  listMyRunsApiV1MeRunsGet,
  loginApiV1AuthLoginPost,
  type Options,
  publishAgentApiV1AgentsAgentIdPublishPost,
  rootGet,
  submitFeedbackApiV1AgentsAgentIdFeedbackPost,
  submitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPost,
  updateAgentApiV1AgentsAgentIdPut,
} from "../sdk.gen";
import type {
  CreateAgentApiV1AgentsPostData,
  CreateAgentApiV1AgentsPostError,
  CreateAgentApiV1AgentsPostResponse,
  CreateAgentRunApiV1AgentsAgentIdRunsPostData,
  CreateAgentRunApiV1AgentsAgentIdRunsPostError,
  CreateAgentRunApiV1AgentsAgentIdRunsPostResponse,
  CreateChallengeApiV1AuthChallengePostData,
  CreateChallengeApiV1AuthChallengePostError,
  CreateChallengeApiV1AuthChallengePostResponse,
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostData,
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostError,
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponse,
  DeleteAgentApiV1AgentsAgentIdDeleteData,
  DeleteAgentApiV1AgentsAgentIdDeleteError,
  DeleteAgentApiV1AgentsAgentIdDeleteResponse,
  GetAgentApiV1AgentsAgentIdGetData,
  GetAgentRunApiV1AgentsAgentIdRunsRunIdGetData,
  GetCurrentUserProfileApiV1AuthMeGetData,
  GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetData,
  GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetData,
  HealthHealthGetData,
  ListAgentsApiV1AgentsGetData,
  ListAgentsApiV1AgentsGetError,
  ListAgentsApiV1AgentsGetResponse,
  ListDataSourcesApiV1ConfigDataSourcesGetData,
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetData,
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetError,
  ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponse,
  ListLlmProvidersApiV1ConfigLlmProvidersGetData,
  ListMyAgentsApiV1MeAgentsGetData,
  ListMyAgentsApiV1MeAgentsGetError,
  ListMyAgentsApiV1MeAgentsGetResponse,
  ListMyRunsApiV1MeRunsGetData,
  ListMyRunsApiV1MeRunsGetError,
  ListMyRunsApiV1MeRunsGetResponse,
  LoginApiV1AuthLoginPostData,
  LoginApiV1AuthLoginPostError,
  LoginApiV1AuthLoginPostResponse,
  PublishAgentApiV1AgentsAgentIdPublishPostData,
  PublishAgentApiV1AgentsAgentIdPublishPostError,
  PublishAgentApiV1AgentsAgentIdPublishPostResponse,
  RootGetData,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostData,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostError,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponse,
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostData,
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostError,
  SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponse,
  UpdateAgentApiV1AgentsAgentIdPutData,
  UpdateAgentApiV1AgentsAgentIdPutError,
  UpdateAgentApiV1AgentsAgentIdPutResponse,
} from "../types.gen";

/**
 * Get authentication challenge
 *
 * Get authentication challenge.
 *
 * Client provides wallet address and chain ID, server returns nonce and message to sign.
 *
 * Args:
 * request: Authentication challenge request
 *
 * Returns:
 * Authentication challenge response with nonce and message to sign
 *
 * Raises:
 * HTTPException: If cache is full, returns 429 Too Many Requests
 */
export const createChallengeApiV1AuthChallengePostMutation = (
  options?: Partial<Options<CreateChallengeApiV1AuthChallengePostData>>,
): UseMutationOptions<
  CreateChallengeApiV1AuthChallengePostResponse,
  CreateChallengeApiV1AuthChallengePostError,
  Options<CreateChallengeApiV1AuthChallengePostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateChallengeApiV1AuthChallengePostResponse,
    CreateChallengeApiV1AuthChallengePostError,
    Options<CreateChallengeApiV1AuthChallengePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createChallengeApiV1AuthChallengePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Login
 *
 * User login.
 *
 * Client signs the challenge message with wallet private key and submits the signature for verification.
 * Returns JWT access token upon successful verification.
 *
 * Args:
 * request: Login request
 *
 * Returns:
 * Login response with JWT access token and user information
 *
 * Raises:
 * HTTPException: If signature verification fails
 */
export const loginApiV1AuthLoginPostMutation = (
  options?: Partial<Options<LoginApiV1AuthLoginPostData>>,
): UseMutationOptions<
  LoginApiV1AuthLoginPostResponse,
  LoginApiV1AuthLoginPostError,
  Options<LoginApiV1AuthLoginPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginApiV1AuthLoginPostResponse,
    LoginApiV1AuthLoginPostError,
    Options<LoginApiV1AuthLoginPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginApiV1AuthLoginPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getCurrentUserProfileApiV1AuthMeGetQueryKey = (
  options?: Options<GetCurrentUserProfileApiV1AuthMeGetData>,
) => createQueryKey("getCurrentUserProfileApiV1AuthMeGet", options);

/**
 * Get current user information
 *
 * Get current logged-in user profile.
 *
 * Requires valid JWT token in request header.
 *
 * Args:
 * current_user: Current user (injected via dependency)
 *
 * Returns:
 * User profile response
 */
export const getCurrentUserProfileApiV1AuthMeGetOptions = (
  options?: Options<GetCurrentUserProfileApiV1AuthMeGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrentUserProfileApiV1AuthMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrentUserProfileApiV1AuthMeGetQueryKey(options),
  });
};

export const listAgentsApiV1AgentsGetQueryKey = (
  options?: Options<ListAgentsApiV1AgentsGetData>,
) => createQueryKey("listAgentsApiV1AgentsGet", options);

/**
 * Query Agent List
 *
 * Query Agent list (supports pagination and filtering).
 *
 * No authentication required, but unauthenticated users can only see published Agents.
 * Authenticated users can see all their own Agents and published Agents from others.
 *
 * Args:
 * pagination: Pagination parameters
 * is_published: Whether published (optional)
 * owner_id: Owner ID (optional)
 * llm_provider_id: LLM Provider ID (optional)
 * search: Search keyword (optional)
 * current_user: Current user (optional, via dependency injection)
 *
 * Returns:
 * Agent list response
 *
 * Raises:
 * HTTPException: If unauthenticated user tries to query Agents of a specific owner
 */
export const listAgentsApiV1AgentsGetOptions = (
  options?: Options<ListAgentsApiV1AgentsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAgentsApiV1AgentsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAgentsApiV1AgentsGetQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listAgentsApiV1AgentsGetInfiniteQueryKey = (
  options?: Options<ListAgentsApiV1AgentsGetData>,
): QueryKey<Options<ListAgentsApiV1AgentsGetData>> =>
  createQueryKey("listAgentsApiV1AgentsGet", options, true);

/**
 * Query Agent List
 *
 * Query Agent list (supports pagination and filtering).
 *
 * No authentication required, but unauthenticated users can only see published Agents.
 * Authenticated users can see all their own Agents and published Agents from others.
 *
 * Args:
 * pagination: Pagination parameters
 * is_published: Whether published (optional)
 * owner_id: Owner ID (optional)
 * llm_provider_id: LLM Provider ID (optional)
 * search: Search keyword (optional)
 * current_user: Current user (optional, via dependency injection)
 *
 * Returns:
 * Agent list response
 *
 * Raises:
 * HTTPException: If unauthenticated user tries to query Agents of a specific owner
 */
export const listAgentsApiV1AgentsGetInfiniteOptions = (
  options?: Options<ListAgentsApiV1AgentsGetData>,
) => {
  return infiniteQueryOptions<
    ListAgentsApiV1AgentsGetResponse,
    ListAgentsApiV1AgentsGetError,
    InfiniteData<ListAgentsApiV1AgentsGetResponse>,
    QueryKey<Options<ListAgentsApiV1AgentsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListAgentsApiV1AgentsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListAgentsApiV1AgentsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listAgentsApiV1AgentsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listAgentsApiV1AgentsGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Create Agent
 *
 * Create a new Agent.
 *
 * Requires authentication. Only draft status Agents can be created, which can be published to chain later via the publish endpoint.
 *
 * Args:
 * request: Agent creation request
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Created Agent ID
 *
 * Raises:
 * HTTPException: If LLM Provider or DataSource does not exist
 */
export const createAgentApiV1AgentsPostMutation = (
  options?: Partial<Options<CreateAgentApiV1AgentsPostData>>,
): UseMutationOptions<
  CreateAgentApiV1AgentsPostResponse,
  CreateAgentApiV1AgentsPostError,
  Options<CreateAgentApiV1AgentsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAgentApiV1AgentsPostResponse,
    CreateAgentApiV1AgentsPostError,
    Options<CreateAgentApiV1AgentsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAgentApiV1AgentsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Agent
 *
 * Delete Agent.
 *
 * Requires authentication, only the owner can delete.
 *
 * Args:
 * agent_id: Agent ID
 * current_user: Current user (via dependency injection)
 *
 * Raises:
 * HTTPException: If Agent does not exist or no permission
 */
export const deleteAgentApiV1AgentsAgentIdDeleteMutation = (
  options?: Partial<Options<DeleteAgentApiV1AgentsAgentIdDeleteData>>,
): UseMutationOptions<
  DeleteAgentApiV1AgentsAgentIdDeleteResponse,
  DeleteAgentApiV1AgentsAgentIdDeleteError,
  Options<DeleteAgentApiV1AgentsAgentIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteAgentApiV1AgentsAgentIdDeleteResponse,
    DeleteAgentApiV1AgentsAgentIdDeleteError,
    Options<DeleteAgentApiV1AgentsAgentIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAgentApiV1AgentsAgentIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAgentApiV1AgentsAgentIdGetQueryKey = (
  options: Options<GetAgentApiV1AgentsAgentIdGetData>,
) => createQueryKey("getAgentApiV1AgentsAgentIdGet", options);

/**
 * Get Agent Details
 *
 * Get Agent details.
 *
 * No authentication required, but only the owner can view unpublished Agents.
 *
 * Args:
 * agent_id: Agent ID
 * current_user: Current user (optional, via dependency injection)
 *
 * Returns:
 * Agent detail response
 *
 * Raises:
 * HTTPException: If Agent does not exist or no permission to access
 */
export const getAgentApiV1AgentsAgentIdGetOptions = (
  options: Options<GetAgentApiV1AgentsAgentIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAgentApiV1AgentsAgentIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAgentApiV1AgentsAgentIdGetQueryKey(options),
  });
};

/**
 * Update Agent
 *
 * Update Agent.
 *
 * Requires authentication, only the owner can update. Only updates the provided fields.
 *
 * Args:
 * agent_id: Agent ID
 * request: Agent update request
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Updated Agent details
 *
 * Raises:
 * HTTPException: If Agent does not exist, no permission, or update failed
 */
export const updateAgentApiV1AgentsAgentIdPutMutation = (
  options?: Partial<Options<UpdateAgentApiV1AgentsAgentIdPutData>>,
): UseMutationOptions<
  UpdateAgentApiV1AgentsAgentIdPutResponse,
  UpdateAgentApiV1AgentsAgentIdPutError,
  Options<UpdateAgentApiV1AgentsAgentIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateAgentApiV1AgentsAgentIdPutResponse,
    UpdateAgentApiV1AgentsAgentIdPutError,
    Options<UpdateAgentApiV1AgentsAgentIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateAgentApiV1AgentsAgentIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Publish Agent to Chain
 *
 * Publish Agent to chain.
 *
 * Requires authentication, only the owner can publish. Creates an async publish task and returns task ID.
 *
 * Args:
 * agent_id: Agent ID
 * request: Publish request (includes force parameter)
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Publish task details
 *
 * Raises:
 * HTTPException: If Agent does not exist, no permission, or task creation failed
 */
export const publishAgentApiV1AgentsAgentIdPublishPostMutation = (
  options?: Partial<Options<PublishAgentApiV1AgentsAgentIdPublishPostData>>,
): UseMutationOptions<
  PublishAgentApiV1AgentsAgentIdPublishPostResponse,
  PublishAgentApiV1AgentsAgentIdPublishPostError,
  Options<PublishAgentApiV1AgentsAgentIdPublishPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PublishAgentApiV1AgentsAgentIdPublishPostResponse,
    PublishAgentApiV1AgentsAgentIdPublishPostError,
    Options<PublishAgentApiV1AgentsAgentIdPublishPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await publishAgentApiV1AgentsAgentIdPublishPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetQueryKey = (
  options: Options<GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetData>,
) =>
  createQueryKey("getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGet", options);

/**
 * Query Publish Task Status
 *
 * Query Agent publish task status.
 *
 * Used to poll publish progress.
 *
 * Args:
 * agent_id: Agent ID
 * job_id: Task ID
 * current_user: Current user (optional, via dependency injection)
 *
 * Returns:
 * Publish task details
 *
 * Raises:
 * HTTPException: If task does not exist or Agent ID does not match
 */
export const getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetOptions = (
  options: Options<GetPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGet(
        {
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        },
      );
      return data;
    },
    queryKey:
      getPublishJobApiV1AgentsAgentIdPublishJobsJobIdGetQueryKey(options),
  });
};

/**
 * Execute Agent
 *
 * Initiate Agent run.
 *
 * Requires authentication. Creates run instance and triggers async task.
 *
 * **Payment Flow**:
 * 1. First call: If Agent requires payment, creates run record and returns 402 status with payment requirements
 * 2. Second call: With X-PAYMENT header, verifies payment then triggers run task
 *
 * Args:
 * agent_id: Agent ID
 * request_body: run request (contains input data)
 * fastapi_request: FastAPI Request object
 * current_user: current user (via dependency injection)
 * x_payment: X-PAYMENT header (optional, provided on second request)
 *
 * Returns:
 * - 202: AgentRunResponse - run created
 * - 402: PaymentRequiredResponse - payment required
 *
 * Raises:
 * HTTPException: if Agent doesn't exist or operation fails
 */
export const createAgentRunApiV1AgentsAgentIdRunsPostMutation = (
  options?: Partial<Options<CreateAgentRunApiV1AgentsAgentIdRunsPostData>>,
): UseMutationOptions<
  CreateAgentRunApiV1AgentsAgentIdRunsPostResponse,
  CreateAgentRunApiV1AgentsAgentIdRunsPostError,
  Options<CreateAgentRunApiV1AgentsAgentIdRunsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAgentRunApiV1AgentsAgentIdRunsPostResponse,
    CreateAgentRunApiV1AgentsAgentIdRunsPostError,
    Options<CreateAgentRunApiV1AgentsAgentIdRunsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAgentRunApiV1AgentsAgentIdRunsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAgentRunApiV1AgentsAgentIdRunsRunIdGetQueryKey = (
  options: Options<GetAgentRunApiV1AgentsAgentIdRunsRunIdGetData>,
) => createQueryKey("getAgentRunApiV1AgentsAgentIdRunsRunIdGet", options);

/**
 * Query Agent run status
 *
 * Query Agent run status.
 *
 * Used for polling run progress. Requires authentication, can only query own runs.
 *
 * Args:
 * agent_id: Agent ID
 * run_id: run ID
 * current_user: current user (via dependency injection)
 *
 * Returns:
 * run details (including event list)
 *
 * Raises:
 * HTTPException: if run doesn't exist or no permission
 */
export const getAgentRunApiV1AgentsAgentIdRunsRunIdGetOptions = (
  options: Options<GetAgentRunApiV1AgentsAgentIdRunsRunIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAgentRunApiV1AgentsAgentIdRunsRunIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAgentRunApiV1AgentsAgentIdRunsRunIdGetQueryKey(options),
  });
};

export const listFeedbacksApiV1AgentsAgentIdFeedbackGetQueryKey = (
  options: Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>,
) => createQueryKey("listFeedbacksApiV1AgentsAgentIdFeedbackGet", options);

/**
 * Query feedback list
 *
 * Query feedback list for Agent.
 *
 * Supports pagination and operation type filtering. No authentication required, everyone can view feedback.
 *
 * Args:
 * agent_id: Agent ID
 * pagination: Pagination parameters
 * operation: Operation type filter (optional)
 *
 * Returns:
 * Feedback list response
 */
export const listFeedbacksApiV1AgentsAgentIdFeedbackGetOptions = (
  options: Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listFeedbacksApiV1AgentsAgentIdFeedbackGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listFeedbacksApiV1AgentsAgentIdFeedbackGetQueryKey(options),
  });
};

export const listFeedbacksApiV1AgentsAgentIdFeedbackGetInfiniteQueryKey = (
  options: Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>,
): QueryKey<Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>> =>
  createQueryKey("listFeedbacksApiV1AgentsAgentIdFeedbackGet", options, true);

/**
 * Query feedback list
 *
 * Query feedback list for Agent.
 *
 * Supports pagination and operation type filtering. No authentication required, everyone can view feedback.
 *
 * Args:
 * agent_id: Agent ID
 * pagination: Pagination parameters
 * operation: Operation type filter (optional)
 *
 * Returns:
 * Feedback list response
 */
export const listFeedbacksApiV1AgentsAgentIdFeedbackGetInfiniteOptions = (
  options: Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>,
) => {
  return infiniteQueryOptions<
    ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponse,
    ListFeedbacksApiV1AgentsAgentIdFeedbackGetError,
    InfiniteData<ListFeedbacksApiV1AgentsAgentIdFeedbackGetResponse>,
    QueryKey<Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListFeedbacksApiV1AgentsAgentIdFeedbackGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listFeedbacksApiV1AgentsAgentIdFeedbackGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey:
        listFeedbacksApiV1AgentsAgentIdFeedbackGetInfiniteQueryKey(options),
    },
  );
};

/**
 * Submit/revoke/respond to feedback
 *
 * Submit, revoke, or append response to feedback.
 *
 * Currently only supports the respond operation; for submit/revoke use the auth + receipts flow.
 *
 * Authentication required. Only published Agents can accept feedback.
 *
 * Args:
 * agent_id: Agent ID
 * request: Feedback request
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Feedback job response (task will be processed asynchronously)
 *
 * Raises:
 * HTTPException: If Agent does not exist, is not published, or user lacks permission
 */
export const submitFeedbackApiV1AgentsAgentIdFeedbackPostMutation = (
  options?: Partial<Options<SubmitFeedbackApiV1AgentsAgentIdFeedbackPostData>>,
): UseMutationOptions<
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponse,
  SubmitFeedbackApiV1AgentsAgentIdFeedbackPostError,
  Options<SubmitFeedbackApiV1AgentsAgentIdFeedbackPostData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmitFeedbackApiV1AgentsAgentIdFeedbackPostResponse,
    SubmitFeedbackApiV1AgentsAgentIdFeedbackPostError,
    Options<SubmitFeedbackApiV1AgentsAgentIdFeedbackPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await submitFeedbackApiV1AgentsAgentIdFeedbackPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Generate feedback authorization
 *
 * Generate feedback authorization signature.
 */
export const createFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostMutation = (
  options?: Partial<
    Options<CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostData>
  >,
): UseMutationOptions<
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponse,
  CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostError,
  Options<CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostResponse,
    CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostError,
    Options<CreateFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await createFeedbackAuthApiV1AgentsAgentIdFeedbackAuthPost({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Sync on-chain feedback receipt
 *
 * Submit feedback receipt signed by client.
 */
export const submitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostMutation =
  (
    options?: Partial<
      Options<SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostData>
    >,
  ): UseMutationOptions<
    SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponse,
    SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostError,
    Options<SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostResponse,
      SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostError,
      Options<SubmitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await submitFeedbackReceiptApiV1AgentsAgentIdFeedbackReceiptsPost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

export const getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetQueryKey = (
  options: Options<GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetData>,
) =>
  createQueryKey(
    "getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGet",
    options,
  );

/**
 * Query feedback job status
 *
 * Query feedback job status.
 *
 * Used by frontend to poll task progress. Authentication required, can only query own tasks or completed tasks.
 *
 * Args:
 * agent_id: Agent ID (for path completeness, not actually used)
 * job_id: Task ID
 * current_user: Current user (via dependency injection)
 *
 * Returns:
 * Feedback job response
 *
 * Raises:
 * HTTPException: If task does not exist or no permission
 */
export const getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetOptions = (
  options: Options<GetFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGet({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey:
      getFeedbackJobApiV1AgentsAgentIdFeedbackJobsJobIdGetQueryKey(options),
  });
};

export const listMyAgentsApiV1MeAgentsGetQueryKey = (
  options?: Options<ListMyAgentsApiV1MeAgentsGetData>,
) => createQueryKey("listMyAgentsApiV1MeAgentsGet", options);

/**
 * View My Agents
 *
 * List all Agents created by the current user.
 *
 * Includes both published and unpublished Agents.
 * Requires authentication.
 *
 * Args:
 * current_user: Current user (via dependency injection)
 * pagination: Pagination parameters
 *
 * Returns:
 * Paginated list of Agents
 */
export const listMyAgentsApiV1MeAgentsGetOptions = (
  options?: Options<ListMyAgentsApiV1MeAgentsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMyAgentsApiV1MeAgentsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listMyAgentsApiV1MeAgentsGetQueryKey(options),
  });
};

export const listMyAgentsApiV1MeAgentsGetInfiniteQueryKey = (
  options?: Options<ListMyAgentsApiV1MeAgentsGetData>,
): QueryKey<Options<ListMyAgentsApiV1MeAgentsGetData>> =>
  createQueryKey("listMyAgentsApiV1MeAgentsGet", options, true);

/**
 * View My Agents
 *
 * List all Agents created by the current user.
 *
 * Includes both published and unpublished Agents.
 * Requires authentication.
 *
 * Args:
 * current_user: Current user (via dependency injection)
 * pagination: Pagination parameters
 *
 * Returns:
 * Paginated list of Agents
 */
export const listMyAgentsApiV1MeAgentsGetInfiniteOptions = (
  options?: Options<ListMyAgentsApiV1MeAgentsGetData>,
) => {
  return infiniteQueryOptions<
    ListMyAgentsApiV1MeAgentsGetResponse,
    ListMyAgentsApiV1MeAgentsGetError,
    InfiniteData<ListMyAgentsApiV1MeAgentsGetResponse>,
    QueryKey<Options<ListMyAgentsApiV1MeAgentsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListMyAgentsApiV1MeAgentsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListMyAgentsApiV1MeAgentsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listMyAgentsApiV1MeAgentsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listMyAgentsApiV1MeAgentsGetInfiniteQueryKey(options),
    },
  );
};

export const listMyRunsApiV1MeRunsGetQueryKey = (
  options?: Options<ListMyRunsApiV1MeRunsGetData>,
) => createQueryKey("listMyRunsApiV1MeRunsGet", options);

/**
 * View My Execution History
 *
 * View all Agent execution history initiated by the current user.
 *
 * Returns in descending order by creation time.
 * Requires authentication.
 *
 * Args:
 * current_user: Current user (via dependency injection)
 * pagination: Pagination parameters
 *
 * Returns:
 * Paginated list of execution history
 */
export const listMyRunsApiV1MeRunsGetOptions = (
  options?: Options<ListMyRunsApiV1MeRunsGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMyRunsApiV1MeRunsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listMyRunsApiV1MeRunsGetQueryKey(options),
  });
};

export const listMyRunsApiV1MeRunsGetInfiniteQueryKey = (
  options?: Options<ListMyRunsApiV1MeRunsGetData>,
): QueryKey<Options<ListMyRunsApiV1MeRunsGetData>> =>
  createQueryKey("listMyRunsApiV1MeRunsGet", options, true);

/**
 * View My Execution History
 *
 * View all Agent execution history initiated by the current user.
 *
 * Returns in descending order by creation time.
 * Requires authentication.
 *
 * Args:
 * current_user: Current user (via dependency injection)
 * pagination: Pagination parameters
 *
 * Returns:
 * Paginated list of execution history
 */
export const listMyRunsApiV1MeRunsGetInfiniteOptions = (
  options?: Options<ListMyRunsApiV1MeRunsGetData>,
) => {
  return infiniteQueryOptions<
    ListMyRunsApiV1MeRunsGetResponse,
    ListMyRunsApiV1MeRunsGetError,
    InfiniteData<ListMyRunsApiV1MeRunsGetResponse>,
    QueryKey<Options<ListMyRunsApiV1MeRunsGetData>>,
    | number
    | Pick<
        QueryKey<Options<ListMyRunsApiV1MeRunsGetData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListMyRunsApiV1MeRunsGetData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listMyRunsApiV1MeRunsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listMyRunsApiV1MeRunsGetInfiniteQueryKey(options),
    },
  );
};

export const listLlmProvidersApiV1ConfigLlmProvidersGetQueryKey = (
  options?: Options<ListLlmProvidersApiV1ConfigLlmProvidersGetData>,
) => createQueryKey("listLlmProvidersApiV1ConfigLlmProvidersGet", options);

/**
 * Query LLM Provider List
 *
 * Query available LLM Provider list.
 *
 * No authentication required, returns all configured LLM Providers.
 *
 * Returns:
 * List of LLM Providers
 */
export const listLlmProvidersApiV1ConfigLlmProvidersGetOptions = (
  options?: Options<ListLlmProvidersApiV1ConfigLlmProvidersGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listLlmProvidersApiV1ConfigLlmProvidersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listLlmProvidersApiV1ConfigLlmProvidersGetQueryKey(options),
  });
};

export const listDataSourcesApiV1ConfigDataSourcesGetQueryKey = (
  options?: Options<ListDataSourcesApiV1ConfigDataSourcesGetData>,
) => createQueryKey("listDataSourcesApiV1ConfigDataSourcesGet", options);

/**
 * Query DataSource List
 *
 * Query available DataSource list.
 *
 * No authentication required, returns all configured DataSources.
 *
 * Returns:
 * List of DataSources
 */
export const listDataSourcesApiV1ConfigDataSourcesGetOptions = (
  options?: Options<ListDataSourcesApiV1ConfigDataSourcesGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listDataSourcesApiV1ConfigDataSourcesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listDataSourcesApiV1ConfigDataSourcesGetQueryKey(options),
  });
};

export const rootGetQueryKey = (options?: Options<RootGetData>) =>
  createQueryKey("rootGet", options);

/**
 * Root
 *
 * Root path health check.
 */
export const rootGetOptions = (options?: Options<RootGetData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await rootGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: rootGetQueryKey(options),
  });
};

export const healthHealthGetQueryKey = (
  options?: Options<HealthHealthGetData>,
) => createQueryKey("healthHealthGet", options);

/**
 * Health
 *
 * Health check endpoint.
 *
 * Checks the status of critical dependencies like database, Redis, Celery, etc.
 */
export const healthHealthGetOptions = (
  options?: Options<HealthHealthGetData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthHealthGetQueryKey(options),
  });
};
